run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - ineffassign
    - nolintlint
    - revive
    - staticcheck
    - typecheck
    - unused
    - govet

linters-settings:
  gocyclo:
    min-complexity: 20
  revive:
    rules:
      - name: empty-block
        disabled: true

issues:
  exclude-dirs:
    - bin
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
