run:
  timeout: 5m
  # Recommended to add
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec      # Add security checks
    - gosimple   # Add simplification checks
    - ineffassign
    - misspell   # Add spell check
    - nolintlint
    - revive
    - staticcheck
    - typecheck
    - govet
    - contextcheck

linters-settings:
  gocyclo:
    min-complexity: 15  # Lower the complexity threshold
  gocritic:
    enabled-checkers:
      - switchDefault
  revive:
    rules:
      - name: empty-block
        disabled: true

issues:
  exclude-dirs-use-default: true  # Add default exclusions
  exclude-dirs:
    - bin
    # vendor directory usually does not need to be explicitly excluded
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
