// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/model/card.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Card 表示一张行动卡。
type Card struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                         // 唯一标识符
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                     // 卡牌名称
	CardType          CardType               `protobuf:"varint,3,opt,name=card_type,json=cardType,proto3,enum=model.CardType" json:"card_type,omitempty"`                        // 卡牌类型
	OwnerRole         PlayerRole             `protobuf:"varint,4,opt,name=owner_role,json=ownerRole,proto3,enum=model.PlayerRole" json:"owner_role,omitempty"`                   // 所属玩家角色（主谋或主角）
	TargetType        string                 `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`                                       // 目标类型（"Character" 或 "Location"）
	Effect            *Effect                `protobuf:"bytes,6,opt,name=effect,proto3" json:"effect,omitempty"`                                                                 // 卡牌效果
	OncePerLoop       bool                   `protobuf:"varint,7,opt,name=once_per_loop,json=oncePerLoop,proto3" json:"once_per_loop,omitempty"`                                 // 每循环只能使用一次
	UsedThisLoop      bool                   `protobuf:"varint,8,opt,name=used_this_loop,json=usedThisLoop,proto3" json:"used_this_loop,omitempty"`                              // 运行时状态
	TargetCharacterId string                 `protobuf:"bytes,9,opt,name=target_character_id,json=targetCharacterId,proto3" json:"target_character_id,omitempty"`                // 目标角色ID
	TargetLocation    LocationType           `protobuf:"varint,10,opt,name=target_location,json=targetLocation,proto3,enum=model.LocationType" json:"target_location,omitempty"` // 目标位置
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_proto_model_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_proto_model_card_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Card) GetCardType() CardType {
	if x != nil {
		return x.CardType
	}
	return CardType_CARD_TYPE_UNSPECIFIED
}

func (x *Card) GetOwnerRole() PlayerRole {
	if x != nil {
		return x.OwnerRole
	}
	return PlayerRole_PLAYER_ROLE_UNSPECIFIED
}

func (x *Card) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *Card) GetEffect() *Effect {
	if x != nil {
		return x.Effect
	}
	return nil
}

func (x *Card) GetOncePerLoop() bool {
	if x != nil {
		return x.OncePerLoop
	}
	return false
}

func (x *Card) GetUsedThisLoop() bool {
	if x != nil {
		return x.UsedThisLoop
	}
	return false
}

func (x *Card) GetTargetCharacterId() string {
	if x != nil {
		return x.TargetCharacterId
	}
	return ""
}

func (x *Card) GetTargetLocation() LocationType {
	if x != nil {
		return x.TargetLocation
	}
	return LocationType_LOCATION_TYPE_UNSPECIFIED
}

type CardList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardList) Reset() {
	*x = CardList{}
	mi := &file_proto_model_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardList) ProtoMessage() {}

func (x *CardList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardList.ProtoReflect.Descriptor instead.
func (*CardList) Descriptor() ([]byte, []int) {
	return file_proto_model_card_proto_rawDescGZIP(), []int{1}
}

func (x *CardList) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

var File_proto_model_card_proto protoreflect.FileDescriptor

const file_proto_model_card_proto_rawDesc = "" +
	"\n" +
	"\x16proto/model/card.proto\x12\x05model\x1a\x18proto/model/effect.proto\x1a\x1aproto/model/location.proto\x1a\x17proto/model/enums.proto\"\x8a\x03\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\tcard_type\x18\x03 \x01(\x0e2\x0f.model.CardTypeR\bcardType\x120\n" +
	"\n" +
	"owner_role\x18\x04 \x01(\x0e2\x11.model.PlayerRoleR\townerRole\x12\x1f\n" +
	"\vtarget_type\x18\x05 \x01(\tR\n" +
	"targetType\x12%\n" +
	"\x06effect\x18\x06 \x01(\v2\r.model.EffectR\x06effect\x12\"\n" +
	"\ronce_per_loop\x18\a \x01(\bR\voncePerLoop\x12$\n" +
	"\x0eused_this_loop\x18\b \x01(\bR\fusedThisLoop\x12.\n" +
	"\x13target_character_id\x18\t \x01(\tR\x11targetCharacterId\x12<\n" +
	"\x0ftarget_location\x18\n" +
	" \x01(\x0e2\x13.model.LocationTypeR\x0etargetLocation\"-\n" +
	"\bCardList\x12!\n" +
	"\x05cards\x18\x01 \x03(\v2\v.model.CardR\x05cardsB\"Z github.com/user/repo/proto/modelb\x06proto3"

var (
	file_proto_model_card_proto_rawDescOnce sync.Once
	file_proto_model_card_proto_rawDescData []byte
)

func file_proto_model_card_proto_rawDescGZIP() []byte {
	file_proto_model_card_proto_rawDescOnce.Do(func() {
		file_proto_model_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_model_card_proto_rawDesc), len(file_proto_model_card_proto_rawDesc)))
	})
	return file_proto_model_card_proto_rawDescData
}

var file_proto_model_card_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_model_card_proto_goTypes = []any{
	(*Card)(nil),      // 0: model.Card
	(*CardList)(nil),  // 1: model.CardList
	(CardType)(0),     // 2: model.CardType
	(PlayerRole)(0),   // 3: model.PlayerRole
	(*Effect)(nil),    // 4: model.Effect
	(LocationType)(0), // 5: model.LocationType
}
var file_proto_model_card_proto_depIdxs = []int32{
	2, // 0: model.Card.card_type:type_name -> model.CardType
	3, // 1: model.Card.owner_role:type_name -> model.PlayerRole
	4, // 2: model.Card.effect:type_name -> model.Effect
	5, // 3: model.Card.target_location:type_name -> model.LocationType
	0, // 4: model.CardList.cards:type_name -> model.Card
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_model_card_proto_init() }
func file_proto_model_card_proto_init() {
	if File_proto_model_card_proto != nil {
		return
	}
	file_proto_model_effect_proto_init()
	file_proto_model_location_proto_init()
	file_proto_model_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_model_card_proto_rawDesc), len(file_proto_model_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_card_proto_goTypes,
		DependencyIndexes: file_proto_model_card_proto_depIdxs,
		MessageInfos:      file_proto_model_card_proto_msgTypes,
	}.Build()
	File_proto_model_card_proto = out.File
	file_proto_model_card_proto_goTypes = nil
	file_proto_model_card_proto_depIdxs = nil
}
