// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/model/effect.proto

package model

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Effect 接口定义了一个效果的核心行为。
type Effect struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to EffectOneof:
	//
	//	*Effect_MoveCharacterEffect
	//	*Effect_AdjustParanoiaEffect
	//	*Effect_AdjustGoodwillEffect
	//	*Effect_AdjustIntrigueEffect
	EffectOneof   isEffect_EffectOneof `protobuf_oneof:"effect_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect) Reset() {
	*x = Effect{}
	mi := &file_proto_model_effect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_effect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect.ProtoReflect.Descriptor instead.
func (*Effect) Descriptor() ([]byte, []int) {
	return file_proto_model_effect_proto_rawDescGZIP(), []int{0}
}

func (x *Effect) GetEffectOneof() isEffect_EffectOneof {
	if x != nil {
		return x.EffectOneof
	}
	return nil
}

func (x *Effect) GetMoveCharacterEffect() *MoveCharacterEffect {
	if x != nil {
		if x, ok := x.EffectOneof.(*Effect_MoveCharacterEffect); ok {
			return x.MoveCharacterEffect
		}
	}
	return nil
}

func (x *Effect) GetAdjustParanoiaEffect() *AdjustParanoiaEffect {
	if x != nil {
		if x, ok := x.EffectOneof.(*Effect_AdjustParanoiaEffect); ok {
			return x.AdjustParanoiaEffect
		}
	}
	return nil
}

func (x *Effect) GetAdjustGoodwillEffect() *AdjustGoodwillEffect {
	if x != nil {
		if x, ok := x.EffectOneof.(*Effect_AdjustGoodwillEffect); ok {
			return x.AdjustGoodwillEffect
		}
	}
	return nil
}

func (x *Effect) GetAdjustIntrigueEffect() *AdjustIntrigueEffect {
	if x != nil {
		if x, ok := x.EffectOneof.(*Effect_AdjustIntrigueEffect); ok {
			return x.AdjustIntrigueEffect
		}
	}
	return nil
}

type isEffect_EffectOneof interface {
	isEffect_EffectOneof()
}

type Effect_MoveCharacterEffect struct {
	MoveCharacterEffect *MoveCharacterEffect `protobuf:"bytes,1,opt,name=move_character_effect,json=moveCharacterEffect,proto3,oneof"`
}

type Effect_AdjustParanoiaEffect struct {
	AdjustParanoiaEffect *AdjustParanoiaEffect `protobuf:"bytes,2,opt,name=adjust_paranoia_effect,json=adjustParanoiaEffect,proto3,oneof"`
}

type Effect_AdjustGoodwillEffect struct {
	AdjustGoodwillEffect *AdjustGoodwillEffect `protobuf:"bytes,3,opt,name=adjust_goodwill_effect,json=adjustGoodwillEffect,proto3,oneof"`
}

type Effect_AdjustIntrigueEffect struct {
	AdjustIntrigueEffect *AdjustIntrigueEffect `protobuf:"bytes,4,opt,name=adjust_intrigue_effect,json=adjustIntrigueEffect,proto3,oneof"`
}

func (*Effect_MoveCharacterEffect) isEffect_EffectOneof() {}

func (*Effect_AdjustParanoiaEffect) isEffect_EffectOneof() {}

func (*Effect_AdjustGoodwillEffect) isEffect_EffectOneof() {}

func (*Effect_AdjustIntrigueEffect) isEffect_EffectOneof() {}

// MoveCharacterEffect 移动一个角色到指定地点。
type MoveCharacterEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   LocationType           `protobuf:"varint,1,opt,name=destination,proto3,enum=model.LocationType" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveCharacterEffect) Reset() {
	*x = MoveCharacterEffect{}
	mi := &file_proto_model_effect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveCharacterEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveCharacterEffect) ProtoMessage() {}

func (x *MoveCharacterEffect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_effect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveCharacterEffect.ProtoReflect.Descriptor instead.
func (*MoveCharacterEffect) Descriptor() ([]byte, []int) {
	return file_proto_model_effect_proto_rawDescGZIP(), []int{1}
}

func (x *MoveCharacterEffect) GetDestination() LocationType {
	if x != nil {
		return x.Destination
	}
	return LocationType_LOCATION_TYPE_UNSPECIFIED
}

// AdjustParanoiaEffect 调整角色的妄想值。
type AdjustParanoiaEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustParanoiaEffect) Reset() {
	*x = AdjustParanoiaEffect{}
	mi := &file_proto_model_effect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustParanoiaEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustParanoiaEffect) ProtoMessage() {}

func (x *AdjustParanoiaEffect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_effect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustParanoiaEffect.ProtoReflect.Descriptor instead.
func (*AdjustParanoiaEffect) Descriptor() ([]byte, []int) {
	return file_proto_model_effect_proto_rawDescGZIP(), []int{2}
}

func (x *AdjustParanoiaEffect) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// AdjustGoodwillEffect 调整角色的好感度。
type AdjustGoodwillEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustGoodwillEffect) Reset() {
	*x = AdjustGoodwillEffect{}
	mi := &file_proto_model_effect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustGoodwillEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustGoodwillEffect) ProtoMessage() {}

func (x *AdjustGoodwillEffect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_effect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustGoodwillEffect.ProtoReflect.Descriptor instead.
func (*AdjustGoodwillEffect) Descriptor() ([]byte, []int) {
	return file_proto_model_effect_proto_rawDescGZIP(), []int{3}
}

func (x *AdjustGoodwillEffect) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// AdjustIntrigueEffect 调整角色的阴谋值。
type AdjustIntrigueEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustIntrigueEffect) Reset() {
	*x = AdjustIntrigueEffect{}
	mi := &file_proto_model_effect_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustIntrigueEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustIntrigueEffect) ProtoMessage() {}

func (x *AdjustIntrigueEffect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_effect_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustIntrigueEffect.ProtoReflect.Descriptor instead.
func (*AdjustIntrigueEffect) Descriptor() ([]byte, []int) {
	return file_proto_model_effect_proto_rawDescGZIP(), []int{4}
}

func (x *AdjustIntrigueEffect) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_proto_model_effect_proto protoreflect.FileDescriptor

const file_proto_model_effect_proto_rawDesc = "" +
	"\n" +
	"\x18proto/model/effect.proto\x12\x05model\x1a\x1aproto/model/location.proto\"\xe9\x02\n" +
	"\x06Effect\x12P\n" +
	"\x15move_character_effect\x18\x01 \x01(\v2\x1a.model.MoveCharacterEffectH\x00R\x13moveCharacterEffect\x12S\n" +
	"\x16adjust_paranoia_effect\x18\x02 \x01(\v2\x1b.model.AdjustParanoiaEffectH\x00R\x14adjustParanoiaEffect\x12S\n" +
	"\x16adjust_goodwill_effect\x18\x03 \x01(\v2\x1b.model.AdjustGoodwillEffectH\x00R\x14adjustGoodwillEffect\x12S\n" +
	"\x16adjust_intrigue_effect\x18\x04 \x01(\v2\x1b.model.AdjustIntrigueEffectH\x00R\x14adjustIntrigueEffectB\x0e\n" +
	"\feffect_oneof\"L\n" +
	"\x13MoveCharacterEffect\x125\n" +
	"\vdestination\x18\x01 \x01(\x0e2\x13.model.LocationTypeR\vdestination\".\n" +
	"\x14AdjustParanoiaEffect\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\".\n" +
	"\x14AdjustGoodwillEffect\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\".\n" +
	"\x14AdjustIntrigueEffect\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amountB\"Z github.com/user/repo/proto/modelb\x06proto3"

var (
	file_proto_model_effect_proto_rawDescOnce sync.Once
	file_proto_model_effect_proto_rawDescData []byte
)

func file_proto_model_effect_proto_rawDescGZIP() []byte {
	file_proto_model_effect_proto_rawDescOnce.Do(func() {
		file_proto_model_effect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_model_effect_proto_rawDesc), len(file_proto_model_effect_proto_rawDesc)))
	})
	return file_proto_model_effect_proto_rawDescData
}

var file_proto_model_effect_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_model_effect_proto_goTypes = []any{
	(*Effect)(nil),               // 0: model.Effect
	(*MoveCharacterEffect)(nil),  // 1: model.MoveCharacterEffect
	(*AdjustParanoiaEffect)(nil), // 2: model.AdjustParanoiaEffect
	(*AdjustGoodwillEffect)(nil), // 3: model.AdjustGoodwillEffect
	(*AdjustIntrigueEffect)(nil), // 4: model.AdjustIntrigueEffect
	(LocationType)(0),            // 5: model.LocationType
}
var file_proto_model_effect_proto_depIdxs = []int32{
	1, // 0: model.Effect.move_character_effect:type_name -> model.MoveCharacterEffect
	2, // 1: model.Effect.adjust_paranoia_effect:type_name -> model.AdjustParanoiaEffect
	3, // 2: model.Effect.adjust_goodwill_effect:type_name -> model.AdjustGoodwillEffect
	4, // 3: model.Effect.adjust_intrigue_effect:type_name -> model.AdjustIntrigueEffect
	5, // 4: model.MoveCharacterEffect.destination:type_name -> model.LocationType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_model_effect_proto_init() }
func file_proto_model_effect_proto_init() {
	if File_proto_model_effect_proto != nil {
		return
	}
	file_proto_model_location_proto_init()
	file_proto_model_effect_proto_msgTypes[0].OneofWrappers = []any{
		(*Effect_MoveCharacterEffect)(nil),
		(*Effect_AdjustParanoiaEffect)(nil),
		(*Effect_AdjustGoodwillEffect)(nil),
		(*Effect_AdjustIntrigueEffect)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_model_effect_proto_rawDesc), len(file_proto_model_effect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_effect_proto_goTypes,
		DependencyIndexes: file_proto_model_effect_proto_depIdxs,
		MessageInfos:      file_proto_model_effect_proto_msgTypes,
	}.Build()
	File_proto_model_effect_proto = out.File
	file_proto_model_effect_proto_goTypes = nil
	file_proto_model_effect_proto_depIdxs = nil
}
