// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/model/location.proto

package model

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LocationType 定义游戏中的可能地点。
type LocationType int32

const (
	LocationType_LOCATION_TYPE_UNSPECIFIED LocationType = 0
	LocationType_LOCATION_TYPE_HOSPITAL    LocationType = 1 // 医院
	LocationType_LOCATION_TYPE_SHRINE      LocationType = 2 // 神社
	LocationType_LOCATION_TYPE_CITY        LocationType = 3 // 城市
	LocationType_LOCATION_TYPE_SCHOOL      LocationType = 4 // 学校
)

// Enum value maps for LocationType.
var (
	LocationType_name = map[int32]string{
		0: "LOCATION_TYPE_UNSPECIFIED",
		1: "LOCATION_TYPE_HOSPITAL",
		2: "LOCATION_TYPE_SHRINE",
		3: "LOCATION_TYPE_CITY",
		4: "LOCATION_TYPE_SCHOOL",
	}
	LocationType_value = map[string]int32{
		"LOCATION_TYPE_UNSPECIFIED": 0,
		"LOCATION_TYPE_HOSPITAL":    1,
		"LOCATION_TYPE_SHRINE":      2,
		"LOCATION_TYPE_CITY":        3,
		"LOCATION_TYPE_SCHOOL":      4,
	}
)

func (x LocationType) Enum() *LocationType {
	p := new(LocationType)
	*p = x
	return p
}

func (x LocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_model_location_proto_enumTypes[0].Descriptor()
}

func (LocationType) Type() protoreflect.EnumType {
	return &file_proto_model_location_proto_enumTypes[0]
}

func (x LocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocationType.Descriptor instead.
func (LocationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_model_location_proto_rawDescGZIP(), []int{0}
}

var File_proto_model_location_proto protoreflect.FileDescriptor

const file_proto_model_location_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/model/location.proto\x12\x05model*\x95\x01\n" +
	"\fLocationType\x12\x1d\n" +
	"\x19LOCATION_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16LOCATION_TYPE_HOSPITAL\x10\x01\x12\x18\n" +
	"\x14LOCATION_TYPE_SHRINE\x10\x02\x12\x16\n" +
	"\x12LOCATION_TYPE_CITY\x10\x03\x12\x18\n" +
	"\x14LOCATION_TYPE_SCHOOL\x10\x04B\"Z github.com/user/repo/proto/modelb\x06proto3"

var (
	file_proto_model_location_proto_rawDescOnce sync.Once
	file_proto_model_location_proto_rawDescData []byte
)

func file_proto_model_location_proto_rawDescGZIP() []byte {
	file_proto_model_location_proto_rawDescOnce.Do(func() {
		file_proto_model_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_model_location_proto_rawDesc), len(file_proto_model_location_proto_rawDesc)))
	})
	return file_proto_model_location_proto_rawDescData
}

var file_proto_model_location_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_model_location_proto_goTypes = []any{
	(LocationType)(0), // 0: model.LocationType
}
var file_proto_model_location_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_model_location_proto_init() }
func file_proto_model_location_proto_init() {
	if File_proto_model_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_model_location_proto_rawDesc), len(file_proto_model_location_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_location_proto_goTypes,
		DependencyIndexes: file_proto_model_location_proto_depIdxs,
		EnumInfos:         file_proto_model_location_proto_enumTypes,
	}.Build()
	File_proto_model_location_proto = out.File
	file_proto_model_location_proto_goTypes = nil
	file_proto_model_location_proto_depIdxs = nil
}
