// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tragedylooper/v1/ability.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompoundAbility_Operator int32

const (
	CompoundAbility_OPERATOR_UNSPECIFIED CompoundAbility_Operator = 0
	CompoundAbility_OPERATOR_AND         CompoundAbility_Operator = 1
	CompoundAbility_OPERATOR_OR          CompoundAbility_Operator = 2
)

// Enum value maps for CompoundAbility_Operator.
var (
	CompoundAbility_Operator_name = map[int32]string{
		0: "OPERATOR_UNSPECIFIED",
		1: "OPERATOR_AND",
		2: "OPERATOR_OR",
	}
	CompoundAbility_Operator_value = map[string]int32{
		"OPERATOR_UNSPECIFIED": 0,
		"OPERATOR_AND":         1,
		"OPERATOR_OR":          2,
	}
)

func (x CompoundAbility_Operator) Enum() *CompoundAbility_Operator {
	p := new(CompoundAbility_Operator)
	*p = x
	return p
}

func (x CompoundAbility_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompoundAbility_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_tragedylooper_v1_ability_proto_enumTypes[0].Descriptor()
}

func (CompoundAbility_Operator) Type() protoreflect.EnumType {
	return &file_tragedylooper_v1_ability_proto_enumTypes[0]
}

func (x CompoundAbility_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompoundAbility_Operator.Descriptor instead.
func (CompoundAbility_Operator) EnumDescriptor() ([]byte, []int) {
	return file_tragedylooper_v1_ability_proto_rawDescGZIP(), []int{1, 0}
}

type AbilityConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                    // 能力唯一ID
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                 // 能力名称
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                                                   // 能力描述
	TriggerType    TriggerType            `protobuf:"varint,4,opt,name=trigger_type,json=triggerType,proto3,enum=tragedylooper.v1.TriggerType" json:"trigger_type,omitempty"`             // 能力触发时机
	EventFilters   []GameEventType        `protobuf:"varint,5,rep,packed,name=event_filters,json=eventFilters,proto3,enum=tragedylooper.v1.GameEventType" json:"event_filters,omitempty"` // 可选：游戏事件触发时的过滤器
	Effect         *Effect                `protobuf:"bytes,6,opt,name=effect,proto3" json:"effect,omitempty"`                                                                             // 能力效果
	OncePerLoop    bool                   `protobuf:"varint,7,opt,name=once_per_loop,json=oncePerLoop,proto3" json:"once_per_loop,omitempty"`                                             // 是否每循环只能使用一次
	RefusalRole    PlayerRole             `protobuf:"varint,8,opt,name=refusal_role,json=refusalRole,proto3,enum=tragedylooper.v1.PlayerRole" json:"refusal_role,omitempty"`              // 可以拒绝此能力的玩家角色
	IsPassive      bool                   `protobuf:"varint,9,opt,name=is_passive,json=isPassive,proto3" json:"is_passive,omitempty"`                                                     // 是否为被动能力
	IsMandatory    bool                   `protobuf:"varint,10,opt,name=is_mandatory,json=isMandatory,proto3" json:"is_mandatory,omitempty"`                                              // 是否为强制能力（不可拒绝）
	Priority       int32                  `protobuf:"varint,11,opt,name=priority,proto3" json:"priority,omitempty"`                                                                       // 能力结算优先级
	Conditions     []*Condition           `protobuf:"bytes,12,rep,name=conditions,proto3" json:"conditions,omitempty"`
	RequiresChoice bool                   `protobuf:"varint,13,opt,name=requires_choice,json=requiresChoice,proto3" json:"requires_choice,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AbilityConfig) Reset() {
	*x = AbilityConfig{}
	mi := &file_tragedylooper_v1_ability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbilityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityConfig) ProtoMessage() {}

func (x *AbilityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_tragedylooper_v1_ability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityConfig.ProtoReflect.Descriptor instead.
func (*AbilityConfig) Descriptor() ([]byte, []int) {
	return file_tragedylooper_v1_ability_proto_rawDescGZIP(), []int{0}
}

func (x *AbilityConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AbilityConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AbilityConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AbilityConfig) GetTriggerType() TriggerType {
	if x != nil {
		return x.TriggerType
	}
	return TriggerType_TRIGGER_TYPE_UNSPECIFIED
}

func (x *AbilityConfig) GetEventFilters() []GameEventType {
	if x != nil {
		return x.EventFilters
	}
	return nil
}

func (x *AbilityConfig) GetEffect() *Effect {
	if x != nil {
		return x.Effect
	}
	return nil
}

func (x *AbilityConfig) GetOncePerLoop() bool {
	if x != nil {
		return x.OncePerLoop
	}
	return false
}

func (x *AbilityConfig) GetRefusalRole() PlayerRole {
	if x != nil {
		return x.RefusalRole
	}
	return PlayerRole_PLAYER_ROLE_UNSPECIFIED
}

func (x *AbilityConfig) GetIsPassive() bool {
	if x != nil {
		return x.IsPassive
	}
	return false
}

func (x *AbilityConfig) GetIsMandatory() bool {
	if x != nil {
		return x.IsMandatory
	}
	return false
}

func (x *AbilityConfig) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AbilityConfig) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *AbilityConfig) GetRequiresChoice() bool {
	if x != nil {
		return x.RequiresChoice
	}
	return false
}

type CompoundAbility struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Operator      CompoundAbility_Operator `protobuf:"varint,1,opt,name=operator,proto3,enum=tragedylooper.v1.CompoundAbility_Operator" json:"operator,omitempty"`
	SubAbilities  []*AbilityConfig         `protobuf:"bytes,2,rep,name=sub_abilities,json=subAbilities,proto3" json:"sub_abilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompoundAbility) Reset() {
	*x = CompoundAbility{}
	mi := &file_tragedylooper_v1_ability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompoundAbility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompoundAbility) ProtoMessage() {}

func (x *CompoundAbility) ProtoReflect() protoreflect.Message {
	mi := &file_tragedylooper_v1_ability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompoundAbility.ProtoReflect.Descriptor instead.
func (*CompoundAbility) Descriptor() ([]byte, []int) {
	return file_tragedylooper_v1_ability_proto_rawDescGZIP(), []int{1}
}

func (x *CompoundAbility) GetOperator() CompoundAbility_Operator {
	if x != nil {
		return x.Operator
	}
	return CompoundAbility_OPERATOR_UNSPECIFIED
}

func (x *CompoundAbility) GetSubAbilities() []*AbilityConfig {
	if x != nil {
		return x.SubAbilities
	}
	return nil
}

type Ability struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Config           *AbilityConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`                                    // 能力ID，关联到AbilityConfig
	UsedThisLoop     bool                   `protobuf:"varint,2,opt,name=used_this_loop,json=usedThisLoop,proto3" json:"used_this_loop,omitempty"` // 运行时状态：本循环是否已使用
	OwnerCharacterId int32                  `protobuf:"varint,3,opt,name=owner_character_id,json=ownerCharacterId,proto3" json:"owner_character_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Ability) Reset() {
	*x = Ability{}
	mi := &file_tragedylooper_v1_ability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ability) ProtoMessage() {}

func (x *Ability) ProtoReflect() protoreflect.Message {
	mi := &file_tragedylooper_v1_ability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ability.ProtoReflect.Descriptor instead.
func (*Ability) Descriptor() ([]byte, []int) {
	return file_tragedylooper_v1_ability_proto_rawDescGZIP(), []int{2}
}

func (x *Ability) GetConfig() *AbilityConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Ability) GetUsedThisLoop() bool {
	if x != nil {
		return x.UsedThisLoop
	}
	return false
}

func (x *Ability) GetOwnerCharacterId() int32 {
	if x != nil {
		return x.OwnerCharacterId
	}
	return 0
}

type AbilityConfigLib struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Abilities     map[int32]*AbilityConfig `protobuf:"bytes,1,rep,name=abilities,proto3" json:"abilities,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 能力ID到配置的映射
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbilityConfigLib) Reset() {
	*x = AbilityConfigLib{}
	mi := &file_tragedylooper_v1_ability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbilityConfigLib) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityConfigLib) ProtoMessage() {}

func (x *AbilityConfigLib) ProtoReflect() protoreflect.Message {
	mi := &file_tragedylooper_v1_ability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityConfigLib.ProtoReflect.Descriptor instead.
func (*AbilityConfigLib) Descriptor() ([]byte, []int) {
	return file_tragedylooper_v1_ability_proto_rawDescGZIP(), []int{3}
}

func (x *AbilityConfigLib) GetAbilities() map[int32]*AbilityConfig {
	if x != nil {
		return x.Abilities
	}
	return nil
}

var File_tragedylooper_v1_ability_proto protoreflect.FileDescriptor

const file_tragedylooper_v1_ability_proto_rawDesc = "" +
	"\n" +
	"\x1etragedylooper/v1/ability.proto\x12\x10tragedylooper.v1\x1a tragedylooper/v1/condition.proto\x1a\x1dtragedylooper/v1/effect.proto\x1a\x1ctragedylooper/v1/enums.proto\"\xb8\x04\n" +
	"\rAbilityConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12@\n" +
	"\ftrigger_type\x18\x04 \x01(\x0e2\x1d.tragedylooper.v1.TriggerTypeR\vtriggerType\x12D\n" +
	"\revent_filters\x18\x05 \x03(\x0e2\x1f.tragedylooper.v1.GameEventTypeR\feventFilters\x120\n" +
	"\x06effect\x18\x06 \x01(\v2\x18.tragedylooper.v1.EffectR\x06effect\x12\"\n" +
	"\ronce_per_loop\x18\a \x01(\bR\voncePerLoop\x12?\n" +
	"\frefusal_role\x18\b \x01(\x0e2\x1c.tragedylooper.v1.PlayerRoleR\vrefusalRole\x12\x1d\n" +
	"\n" +
	"is_passive\x18\t \x01(\bR\tisPassive\x12!\n" +
	"\fis_mandatory\x18\n" +
	" \x01(\bR\visMandatory\x12\x1a\n" +
	"\bpriority\x18\v \x01(\x05R\bpriority\x12;\n" +
	"\n" +
	"conditions\x18\f \x03(\v2\x1b.tragedylooper.v1.ConditionR\n" +
	"conditions\x12'\n" +
	"\x0frequires_choice\x18\r \x01(\bR\x0erequiresChoice\"\xe8\x01\n" +
	"\x0fCompoundAbility\x12F\n" +
	"\boperator\x18\x01 \x01(\x0e2*.tragedylooper.v1.CompoundAbility.OperatorR\boperator\x12D\n" +
	"\rsub_abilities\x18\x02 \x03(\v2\x1f.tragedylooper.v1.AbilityConfigR\fsubAbilities\"G\n" +
	"\bOperator\x12\x18\n" +
	"\x14OPERATOR_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fOPERATOR_AND\x10\x01\x12\x0f\n" +
	"\vOPERATOR_OR\x10\x02\"\x96\x01\n" +
	"\aAbility\x127\n" +
	"\x06config\x18\x01 \x01(\v2\x1f.tragedylooper.v1.AbilityConfigR\x06config\x12$\n" +
	"\x0eused_this_loop\x18\x02 \x01(\bR\fusedThisLoop\x12,\n" +
	"\x12owner_character_id\x18\x03 \x01(\x05R\x10ownerCharacterId\"\xc2\x01\n" +
	"\x10AbilityConfigLib\x12O\n" +
	"\tabilities\x18\x01 \x03(\v21.tragedylooper.v1.AbilityConfigLib.AbilitiesEntryR\tabilities\x1a]\n" +
	"\x0eAbilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.tragedylooper.v1.AbilityConfigR\x05value:\x028\x01B\x1cZ\x1atragedylooper/pkg/proto/v1b\x06proto3"

var (
	file_tragedylooper_v1_ability_proto_rawDescOnce sync.Once
	file_tragedylooper_v1_ability_proto_rawDescData []byte
)

func file_tragedylooper_v1_ability_proto_rawDescGZIP() []byte {
	file_tragedylooper_v1_ability_proto_rawDescOnce.Do(func() {
		file_tragedylooper_v1_ability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tragedylooper_v1_ability_proto_rawDesc), len(file_tragedylooper_v1_ability_proto_rawDesc)))
	})
	return file_tragedylooper_v1_ability_proto_rawDescData
}

var file_tragedylooper_v1_ability_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tragedylooper_v1_ability_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tragedylooper_v1_ability_proto_goTypes = []any{
	(CompoundAbility_Operator)(0), // 0: tragedylooper.v1.CompoundAbility.Operator
	(*AbilityConfig)(nil),         // 1: tragedylooper.v1.AbilityConfig
	(*CompoundAbility)(nil),       // 2: tragedylooper.v1.CompoundAbility
	(*Ability)(nil),               // 3: tragedylooper.v1.Ability
	(*AbilityConfigLib)(nil),      // 4: tragedylooper.v1.AbilityConfigLib
	nil,                           // 5: tragedylooper.v1.AbilityConfigLib.AbilitiesEntry
	(TriggerType)(0),              // 6: tragedylooper.v1.TriggerType
	(GameEventType)(0),            // 7: tragedylooper.v1.GameEventType
	(*Effect)(nil),                // 8: tragedylooper.v1.Effect
	(PlayerRole)(0),               // 9: tragedylooper.v1.PlayerRole
	(*Condition)(nil),             // 10: tragedylooper.v1.Condition
}
var file_tragedylooper_v1_ability_proto_depIdxs = []int32{
	6,  // 0: tragedylooper.v1.AbilityConfig.trigger_type:type_name -> tragedylooper.v1.TriggerType
	7,  // 1: tragedylooper.v1.AbilityConfig.event_filters:type_name -> tragedylooper.v1.GameEventType
	8,  // 2: tragedylooper.v1.AbilityConfig.effect:type_name -> tragedylooper.v1.Effect
	9,  // 3: tragedylooper.v1.AbilityConfig.refusal_role:type_name -> tragedylooper.v1.PlayerRole
	10, // 4: tragedylooper.v1.AbilityConfig.conditions:type_name -> tragedylooper.v1.Condition
	0,  // 5: tragedylooper.v1.CompoundAbility.operator:type_name -> tragedylooper.v1.CompoundAbility.Operator
	1,  // 6: tragedylooper.v1.CompoundAbility.sub_abilities:type_name -> tragedylooper.v1.AbilityConfig
	1,  // 7: tragedylooper.v1.Ability.config:type_name -> tragedylooper.v1.AbilityConfig
	5,  // 8: tragedylooper.v1.AbilityConfigLib.abilities:type_name -> tragedylooper.v1.AbilityConfigLib.AbilitiesEntry
	1,  // 9: tragedylooper.v1.AbilityConfigLib.AbilitiesEntry.value:type_name -> tragedylooper.v1.AbilityConfig
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_tragedylooper_v1_ability_proto_init() }
func file_tragedylooper_v1_ability_proto_init() {
	if File_tragedylooper_v1_ability_proto != nil {
		return
	}
	file_tragedylooper_v1_condition_proto_init()
	file_tragedylooper_v1_effect_proto_init()
	file_tragedylooper_v1_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tragedylooper_v1_ability_proto_rawDesc), len(file_tragedylooper_v1_ability_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tragedylooper_v1_ability_proto_goTypes,
		DependencyIndexes: file_tragedylooper_v1_ability_proto_depIdxs,
		EnumInfos:         file_tragedylooper_v1_ability_proto_enumTypes,
		MessageInfos:      file_tragedylooper_v1_ability_proto_msgTypes,
	}.Build()
	File_tragedylooper_v1_ability_proto = out.File
	file_tragedylooper_v1_ability_proto_goTypes = nil
	file_tragedylooper_v1_ability_proto_depIdxs = nil
}
