// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tragedylooper/v1/card.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CardConfig defines the static, immutable properties of a card.
// This represents a card as it is defined in the game's rulebook or script.
type CardConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier for this type of card.
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the card.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// A user-facing description of the card's effect.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// The type of the card, used for categorization and resolution order.
	Type CardType `protobuf:"varint,4,opt,name=type,proto3,enum=tragedylooper.v1.CardType" json:"type,omitempty"`
	// The role that is allowed to use this card.
	OwnerRole PlayerRole `protobuf:"varint,5,opt,name=owner_role,json=ownerRole,proto3,enum=tragedylooper.v1.PlayerRole" json:"owner_role,omitempty"`
	// The effect or chain of effects the card produces when played.
	Effect *CompoundEffect `protobuf:"bytes,6,opt,name=effect,proto3" json:"effect,omitempty"`
	// If true, this card can only be successfully played once per loop.
	OncePerLoop bool `protobuf:"varint,7,opt,name=once_per_loop,json=oncePerLoop,proto3" json:"once_per_loop,omitempty"`
	// The priority of the card, used to determine resolution order among cards of the same type.
	Priority      int32 `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardConfig) Reset() {
	*x = CardConfig{}
	mi := &file_tragedylooper_v1_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardConfig) ProtoMessage() {}

func (x *CardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_tragedylooper_v1_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardConfig.ProtoReflect.Descriptor instead.
func (*CardConfig) Descriptor() ([]byte, []int) {
	return file_tragedylooper_v1_card_proto_rawDescGZIP(), []int{0}
}

func (x *CardConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CardConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CardConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CardConfig) GetType() CardType {
	if x != nil {
		return x.Type
	}
	return CardType_CARD_TYPE_UNSPECIFIED
}

func (x *CardConfig) GetOwnerRole() PlayerRole {
	if x != nil {
		return x.OwnerRole
	}
	return PlayerRole_PLAYER_ROLE_UNSPECIFIED
}

func (x *CardConfig) GetEffect() *CompoundEffect {
	if x != nil {
		return x.Effect
	}
	return nil
}

func (x *CardConfig) GetOncePerLoop() bool {
	if x != nil {
		return x.OncePerLoop
	}
	return false
}

func (x *CardConfig) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// Card represents an instance of a card in a player's hand or in play.
// It combines the static configuration with dynamic, mutable state.
type Card struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the card, copied from its config for convenience.
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The static configuration of the card.
	Config *CardConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// Whether the card has been used in the current loop.
	UsedThisLoop bool `protobuf:"varint,3,opt,name=used_this_loop,json=usedThisLoop,proto3" json:"used_this_loop,omitempty"`
	// The final, confirmed target for the card's effect, set after any required player choices.
	ResolvedTarget *Choice `protobuf:"bytes,4,opt,name=resolved_target,json=resolvedTarget,proto3" json:"resolved_target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_tragedylooper_v1_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_tragedylooper_v1_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_tragedylooper_v1_card_proto_rawDescGZIP(), []int{1}
}

func (x *Card) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Card) GetConfig() *CardConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Card) GetUsedThisLoop() bool {
	if x != nil {
		return x.UsedThisLoop
	}
	return false
}

func (x *Card) GetResolvedTarget() *Choice {
	if x != nil {
		return x.ResolvedTarget
	}
	return nil
}

// CardList is a collection of card instances, typically representing a player's hand.
type CardList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of card instances.
	Cards         []*Card `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardList) Reset() {
	*x = CardList{}
	mi := &file_tragedylooper_v1_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardList) ProtoMessage() {}

func (x *CardList) ProtoReflect() protoreflect.Message {
	mi := &file_tragedylooper_v1_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardList.ProtoReflect.Descriptor instead.
func (*CardList) Descriptor() ([]byte, []int) {
	return file_tragedylooper_v1_card_proto_rawDescGZIP(), []int{2}
}

func (x *CardList) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

var File_tragedylooper_v1_card_proto protoreflect.FileDescriptor

const file_tragedylooper_v1_card_proto_rawDesc = "" +
	"\n" +
	"\x1btragedylooper/v1/card.proto\x12\x10tragedylooper.v1\x1a\x1dtragedylooper/v1/effect.proto\x1a\x1ctragedylooper/v1/enums.proto\x1a\x1dtragedylooper/v1/common.proto\"\xb9\x02\n" +
	"\n" +
	"CardConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12.\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1a.tragedylooper.v1.CardTypeR\x04type\x12;\n" +
	"\n" +
	"owner_role\x18\x05 \x01(\x0e2\x1c.tragedylooper.v1.PlayerRoleR\townerRole\x128\n" +
	"\x06effect\x18\x06 \x01(\v2 .tragedylooper.v1.CompoundEffectR\x06effect\x12\"\n" +
	"\ronce_per_loop\x18\a \x01(\bR\voncePerLoop\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\"\xb5\x01\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x124\n" +
	"\x06config\x18\x02 \x01(\v2\x1c.tragedylooper.v1.CardConfigR\x06config\x12$\n" +
	"\x0eused_this_loop\x18\x03 \x01(\bR\fusedThisLoop\x12A\n" +
	"\x0fresolved_target\x18\x04 \x01(\v2\x18.tragedylooper.v1.ChoiceR\x0eresolvedTarget\"8\n" +
	"\bCardList\x12,\n" +
	"\x05cards\x18\x01 \x03(\v2\x16.tragedylooper.v1.CardR\x05cardsB\xb9\x01\n" +
	"\x14com.tragedylooper.v1B\tCardProtoP\x01Z5github.com/constellation39/tragedyLooper/pkg/proto/v1\xa2\x02\x03TXX\xaa\x02\x10Tragedylooper.V1\xca\x02\x10Tragedylooper\\V1\xe2\x02\x1cTragedylooper\\V1\\GPBMetadata\xea\x02\x11Tragedylooper::V1b\x06proto3"

var (
	file_tragedylooper_v1_card_proto_rawDescOnce sync.Once
	file_tragedylooper_v1_card_proto_rawDescData []byte
)

func file_tragedylooper_v1_card_proto_rawDescGZIP() []byte {
	file_tragedylooper_v1_card_proto_rawDescOnce.Do(func() {
		file_tragedylooper_v1_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tragedylooper_v1_card_proto_rawDesc), len(file_tragedylooper_v1_card_proto_rawDesc)))
	})
	return file_tragedylooper_v1_card_proto_rawDescData
}

var file_tragedylooper_v1_card_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tragedylooper_v1_card_proto_goTypes = []any{
	(*CardConfig)(nil),     // 0: tragedylooper.v1.CardConfig
	(*Card)(nil),           // 1: tragedylooper.v1.Card
	(*CardList)(nil),       // 2: tragedylooper.v1.CardList
	(CardType)(0),          // 3: tragedylooper.v1.CardType
	(PlayerRole)(0),        // 4: tragedylooper.v1.PlayerRole
	(*CompoundEffect)(nil), // 5: tragedylooper.v1.CompoundEffect
	(*Choice)(nil),         // 6: tragedylooper.v1.Choice
}
var file_tragedylooper_v1_card_proto_depIdxs = []int32{
	3, // 0: tragedylooper.v1.CardConfig.type:type_name -> tragedylooper.v1.CardType
	4, // 1: tragedylooper.v1.CardConfig.owner_role:type_name -> tragedylooper.v1.PlayerRole
	5, // 2: tragedylooper.v1.CardConfig.effect:type_name -> tragedylooper.v1.CompoundEffect
	0, // 3: tragedylooper.v1.Card.config:type_name -> tragedylooper.v1.CardConfig
	6, // 4: tragedylooper.v1.Card.resolved_target:type_name -> tragedylooper.v1.Choice
	1, // 5: tragedylooper.v1.CardList.cards:type_name -> tragedylooper.v1.Card
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_tragedylooper_v1_card_proto_init() }
func file_tragedylooper_v1_card_proto_init() {
	if File_tragedylooper_v1_card_proto != nil {
		return
	}
	file_tragedylooper_v1_effect_proto_init()
	file_tragedylooper_v1_enums_proto_init()
	file_tragedylooper_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tragedylooper_v1_card_proto_rawDesc), len(file_tragedylooper_v1_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tragedylooper_v1_card_proto_goTypes,
		DependencyIndexes: file_tragedylooper_v1_card_proto_depIdxs,
		MessageInfos:      file_tragedylooper_v1_card_proto_msgTypes,
	}.Build()
	File_tragedylooper_v1_card_proto = out.File
	file_tragedylooper_v1_card_proto_goTypes = nil
	file_tragedylooper_v1_card_proto_depIdxs = nil
}
