// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tragedylooper/v1/payload.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家打出卡牌的操作负载
type PlayCardPayload struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CardId int32                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"` // 打出的卡牌ID
	// 可选：预先选择的选项，用于简化交互。
	// 键：来自潜在 ChoiceRequiredEvent 的 request_id
	// 值：来自该事件的 chosen_option_id
	PreChosenOptions map[string]string `protobuf:"bytes,2,rep,name=pre_chosen_options,json=preChosenOptions,proto3" json:"pre_chosen_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlayCardPayload) Reset() {
	*x = PlayCardPayload{}
	mi := &file_tragedylooper_v1_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayCardPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayCardPayload) ProtoMessage() {}

func (x *PlayCardPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tragedylooper_v1_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayCardPayload.ProtoReflect.Descriptor instead.
func (*PlayCardPayload) Descriptor() ([]byte, []int) {
	return file_tragedylooper_v1_payload_proto_rawDescGZIP(), []int{0}
}

func (x *PlayCardPayload) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *PlayCardPayload) GetPreChosenOptions() map[string]string {
	if x != nil {
		return x.PreChosenOptions
	}
	return nil
}

// 玩家使用能力的操作负载
type UseAbilityPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CharacterId      int32                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // 哪个角色的能力被使用
	AbilityId        int32                  `protobuf:"varint,2,opt,name=ability_id,json=abilityId,proto3" json:"ability_id,omitempty"`       // 哪个能力被使用
	PreChosenOptions map[string]string      `protobuf:"bytes,3,rep,name=pre_chosen_options,json=preChosenOptions,proto3" json:"pre_chosen_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UseAbilityPayload) Reset() {
	*x = UseAbilityPayload{}
	mi := &file_tragedylooper_v1_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseAbilityPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseAbilityPayload) ProtoMessage() {}

func (x *UseAbilityPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tragedylooper_v1_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseAbilityPayload.ProtoReflect.Descriptor instead.
func (*UseAbilityPayload) Descriptor() ([]byte, []int) {
	return file_tragedylooper_v1_payload_proto_rawDescGZIP(), []int{1}
}

func (x *UseAbilityPayload) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *UseAbilityPayload) GetAbilityId() int32 {
	if x != nil {
		return x.AbilityId
	}
	return 0
}

func (x *UseAbilityPayload) GetPreChosenOptions() map[string]string {
	if x != nil {
		return x.PreChosenOptions
	}
	return nil
}

// 主角玩家进行猜测的操作负载
type MakeGuessPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuessedRoles  map[int32]int32        `protobuf:"bytes,1,rep,name=guessed_roles,json=guessedRoles,proto3" json:"guessed_roles,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 猜测的角色身份映射，键为 character_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeGuessPayload) Reset() {
	*x = MakeGuessPayload{}
	mi := &file_tragedylooper_v1_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeGuessPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeGuessPayload) ProtoMessage() {}

func (x *MakeGuessPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tragedylooper_v1_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeGuessPayload.ProtoReflect.Descriptor instead.
func (*MakeGuessPayload) Descriptor() ([]byte, []int) {
	return file_tragedylooper_v1_payload_proto_rawDescGZIP(), []int{2}
}

func (x *MakeGuessPayload) GetGuessedRoles() map[int32]int32 {
	if x != nil {
		return x.GuessedRoles
	}
	return nil
}

// 玩家进行选择的操作负载（例如，在需要选择地盘或目标时）
type ChooseOptionPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                  // 我们正在响应的事件ID
	CharacterId    *int32                 `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3,oneof" json:"character_id,omitempty"`     // 做出选择的角色（如果选择与角色相关）
	ChosenOptionId string                 `protobuf:"bytes,3,opt,name=chosen_option_id,json=chosenOptionId,proto3" json:"chosen_option_id,omitempty"` // 选择项的ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChooseOptionPayload) Reset() {
	*x = ChooseOptionPayload{}
	mi := &file_tragedylooper_v1_payload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseOptionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseOptionPayload) ProtoMessage() {}

func (x *ChooseOptionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tragedylooper_v1_payload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseOptionPayload.ProtoReflect.Descriptor instead.
func (*ChooseOptionPayload) Descriptor() ([]byte, []int) {
	return file_tragedylooper_v1_payload_proto_rawDescGZIP(), []int{3}
}

func (x *ChooseOptionPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChooseOptionPayload) GetCharacterId() int32 {
	if x != nil && x.CharacterId != nil {
		return *x.CharacterId
	}
	return 0
}

func (x *ChooseOptionPayload) GetChosenOptionId() string {
	if x != nil {
		return x.ChosenOptionId
	}
	return ""
}

// 玩家跳过回合的操作负载
type PassTurnAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassTurnAction) Reset() {
	*x = PassTurnAction{}
	mi := &file_tragedylooper_v1_payload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassTurnAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassTurnAction) ProtoMessage() {}

func (x *PassTurnAction) ProtoReflect() protoreflect.Message {
	mi := &file_tragedylooper_v1_payload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassTurnAction.ProtoReflect.Descriptor instead.
func (*PassTurnAction) Descriptor() ([]byte, []int) {
	return file_tragedylooper_v1_payload_proto_rawDescGZIP(), []int{4}
}

// 通用的玩家操作负载
type PlayerActionPayload struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PlayerId int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 执行操作的玩家ID
	// Types that are valid to be assigned to Payload:
	//
	//	*PlayerActionPayload_PlayCard
	//	*PlayerActionPayload_UseAbility
	//	*PlayerActionPayload_MakeGuess
	//	*PlayerActionPayload_ChooseOption
	//	*PlayerActionPayload_PassTurn
	Payload       isPlayerActionPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerActionPayload) Reset() {
	*x = PlayerActionPayload{}
	mi := &file_tragedylooper_v1_payload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerActionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerActionPayload) ProtoMessage() {}

func (x *PlayerActionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tragedylooper_v1_payload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerActionPayload.ProtoReflect.Descriptor instead.
func (*PlayerActionPayload) Descriptor() ([]byte, []int) {
	return file_tragedylooper_v1_payload_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerActionPayload) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerActionPayload) GetPayload() isPlayerActionPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PlayerActionPayload) GetPlayCard() *PlayCardPayload {
	if x != nil {
		if x, ok := x.Payload.(*PlayerActionPayload_PlayCard); ok {
			return x.PlayCard
		}
	}
	return nil
}

func (x *PlayerActionPayload) GetUseAbility() *UseAbilityPayload {
	if x != nil {
		if x, ok := x.Payload.(*PlayerActionPayload_UseAbility); ok {
			return x.UseAbility
		}
	}
	return nil
}

func (x *PlayerActionPayload) GetMakeGuess() *MakeGuessPayload {
	if x != nil {
		if x, ok := x.Payload.(*PlayerActionPayload_MakeGuess); ok {
			return x.MakeGuess
		}
	}
	return nil
}

func (x *PlayerActionPayload) GetChooseOption() *ChooseOptionPayload {
	if x != nil {
		if x, ok := x.Payload.(*PlayerActionPayload_ChooseOption); ok {
			return x.ChooseOption
		}
	}
	return nil
}

func (x *PlayerActionPayload) GetPassTurn() *PassTurnAction {
	if x != nil {
		if x, ok := x.Payload.(*PlayerActionPayload_PassTurn); ok {
			return x.PassTurn
		}
	}
	return nil
}

type isPlayerActionPayload_Payload interface {
	isPlayerActionPayload_Payload()
}

type PlayerActionPayload_PlayCard struct {
	PlayCard *PlayCardPayload `protobuf:"bytes,2,opt,name=play_card,json=playCard,proto3,oneof"` // 打出卡牌的负载
}

type PlayerActionPayload_UseAbility struct {
	UseAbility *UseAbilityPayload `protobuf:"bytes,3,opt,name=use_ability,json=useAbility,proto3,oneof"` // 使用能力的负载
}

type PlayerActionPayload_MakeGuess struct {
	MakeGuess *MakeGuessPayload `protobuf:"bytes,4,opt,name=make_guess,json=makeGuess,proto3,oneof"` // 进行猜测的负载
}

type PlayerActionPayload_ChooseOption struct {
	ChooseOption *ChooseOptionPayload `protobuf:"bytes,5,opt,name=choose_option,json=chooseOption,proto3,oneof"` // 进行选择的负载
}

type PlayerActionPayload_PassTurn struct {
	PassTurn *PassTurnAction `protobuf:"bytes,6,opt,name=pass_turn,json=passTurn,proto3,oneof"` // 玩家跳过
}

func (*PlayerActionPayload_PlayCard) isPlayerActionPayload_Payload() {}

func (*PlayerActionPayload_UseAbility) isPlayerActionPayload_Payload() {}

func (*PlayerActionPayload_MakeGuess) isPlayerActionPayload_Payload() {}

func (*PlayerActionPayload_ChooseOption) isPlayerActionPayload_Payload() {}

func (*PlayerActionPayload_PassTurn) isPlayerActionPayload_Payload() {}

var File_tragedylooper_v1_payload_proto protoreflect.FileDescriptor

const file_tragedylooper_v1_payload_proto_rawDesc = "" +
	"\n" +
	"\x1etragedylooper/v1/payload.proto\x12\x10tragedylooper.v1\x1a\x1ctragedylooper/v1/enums.proto\"\xd6\x01\n" +
	"\x0fPlayCardPayload\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x05R\x06cardId\x12e\n" +
	"\x12pre_chosen_options\x18\x02 \x03(\v27.tragedylooper.v1.PlayCardPayload.PreChosenOptionsEntryR\x10preChosenOptions\x1aC\n" +
	"\x15PreChosenOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x02\n" +
	"\x11UseAbilityPayload\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x05R\vcharacterId\x12\x1d\n" +
	"\n" +
	"ability_id\x18\x02 \x01(\x05R\tabilityId\x12g\n" +
	"\x12pre_chosen_options\x18\x03 \x03(\v29.tragedylooper.v1.UseAbilityPayload.PreChosenOptionsEntryR\x10preChosenOptions\x1aC\n" +
	"\x15PreChosenOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x01\n" +
	"\x10MakeGuessPayload\x12Y\n" +
	"\rguessed_roles\x18\x01 \x03(\v24.tragedylooper.v1.MakeGuessPayload.GuessedRolesEntryR\fguessedRoles\x1a?\n" +
	"\x11GuessedRolesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x97\x01\n" +
	"\x13ChooseOptionPayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12&\n" +
	"\fcharacter_id\x18\x02 \x01(\x05H\x00R\vcharacterId\x88\x01\x01\x12(\n" +
	"\x10chosen_option_id\x18\x03 \x01(\tR\x0echosenOptionIdB\x0f\n" +
	"\r_character_id\"\x10\n" +
	"\x0ePassTurnAction\"\x9b\x03\n" +
	"\x13PlayerActionPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\x12@\n" +
	"\tplay_card\x18\x02 \x01(\v2!.tragedylooper.v1.PlayCardPayloadH\x00R\bplayCard\x12F\n" +
	"\vuse_ability\x18\x03 \x01(\v2#.tragedylooper.v1.UseAbilityPayloadH\x00R\n" +
	"useAbility\x12C\n" +
	"\n" +
	"make_guess\x18\x04 \x01(\v2\".tragedylooper.v1.MakeGuessPayloadH\x00R\tmakeGuess\x12L\n" +
	"\rchoose_option\x18\x05 \x01(\v2%.tragedylooper.v1.ChooseOptionPayloadH\x00R\fchooseOption\x12?\n" +
	"\tpass_turn\x18\x06 \x01(\v2 .tragedylooper.v1.PassTurnActionH\x00R\bpassTurnB\t\n" +
	"\apayloadB\xbc\x01\n" +
	"\x14com.tragedylooper.v1B\fPayloadProtoP\x01Z5github.com/constellation39/tragedyLooper/pkg/proto/v1\xa2\x02\x03TXX\xaa\x02\x10Tragedylooper.V1\xca\x02\x10Tragedylooper\\V1\xe2\x02\x1cTragedylooper\\V1\\GPBMetadata\xea\x02\x11Tragedylooper::V1b\x06proto3"

var (
	file_tragedylooper_v1_payload_proto_rawDescOnce sync.Once
	file_tragedylooper_v1_payload_proto_rawDescData []byte
)

func file_tragedylooper_v1_payload_proto_rawDescGZIP() []byte {
	file_tragedylooper_v1_payload_proto_rawDescOnce.Do(func() {
		file_tragedylooper_v1_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tragedylooper_v1_payload_proto_rawDesc), len(file_tragedylooper_v1_payload_proto_rawDesc)))
	})
	return file_tragedylooper_v1_payload_proto_rawDescData
}

var file_tragedylooper_v1_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_tragedylooper_v1_payload_proto_goTypes = []any{
	(*PlayCardPayload)(nil),     // 0: tragedylooper.v1.PlayCardPayload
	(*UseAbilityPayload)(nil),   // 1: tragedylooper.v1.UseAbilityPayload
	(*MakeGuessPayload)(nil),    // 2: tragedylooper.v1.MakeGuessPayload
	(*ChooseOptionPayload)(nil), // 3: tragedylooper.v1.ChooseOptionPayload
	(*PassTurnAction)(nil),      // 4: tragedylooper.v1.PassTurnAction
	(*PlayerActionPayload)(nil), // 5: tragedylooper.v1.PlayerActionPayload
	nil,                         // 6: tragedylooper.v1.PlayCardPayload.PreChosenOptionsEntry
	nil,                         // 7: tragedylooper.v1.UseAbilityPayload.PreChosenOptionsEntry
	nil,                         // 8: tragedylooper.v1.MakeGuessPayload.GuessedRolesEntry
}
var file_tragedylooper_v1_payload_proto_depIdxs = []int32{
	6, // 0: tragedylooper.v1.PlayCardPayload.pre_chosen_options:type_name -> tragedylooper.v1.PlayCardPayload.PreChosenOptionsEntry
	7, // 1: tragedylooper.v1.UseAbilityPayload.pre_chosen_options:type_name -> tragedylooper.v1.UseAbilityPayload.PreChosenOptionsEntry
	8, // 2: tragedylooper.v1.MakeGuessPayload.guessed_roles:type_name -> tragedylooper.v1.MakeGuessPayload.GuessedRolesEntry
	0, // 3: tragedylooper.v1.PlayerActionPayload.play_card:type_name -> tragedylooper.v1.PlayCardPayload
	1, // 4: tragedylooper.v1.PlayerActionPayload.use_ability:type_name -> tragedylooper.v1.UseAbilityPayload
	2, // 5: tragedylooper.v1.PlayerActionPayload.make_guess:type_name -> tragedylooper.v1.MakeGuessPayload
	3, // 6: tragedylooper.v1.PlayerActionPayload.choose_option:type_name -> tragedylooper.v1.ChooseOptionPayload
	4, // 7: tragedylooper.v1.PlayerActionPayload.pass_turn:type_name -> tragedylooper.v1.PassTurnAction
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_tragedylooper_v1_payload_proto_init() }
func file_tragedylooper_v1_payload_proto_init() {
	if File_tragedylooper_v1_payload_proto != nil {
		return
	}
	file_tragedylooper_v1_enums_proto_init()
	file_tragedylooper_v1_payload_proto_msgTypes[3].OneofWrappers = []any{}
	file_tragedylooper_v1_payload_proto_msgTypes[5].OneofWrappers = []any{
		(*PlayerActionPayload_PlayCard)(nil),
		(*PlayerActionPayload_UseAbility)(nil),
		(*PlayerActionPayload_MakeGuess)(nil),
		(*PlayerActionPayload_ChooseOption)(nil),
		(*PlayerActionPayload_PassTurn)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tragedylooper_v1_payload_proto_rawDesc), len(file_tragedylooper_v1_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tragedylooper_v1_payload_proto_goTypes,
		DependencyIndexes: file_tragedylooper_v1_payload_proto_depIdxs,
		MessageInfos:      file_tragedylooper_v1_payload_proto_msgTypes,
	}.Build()
	File_tragedylooper_v1_payload_proto = out.File
	file_tragedylooper_v1_payload_proto_goTypes = nil
	file_tragedylooper_v1_payload_proto_depIdxs = nil
}
