// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/game/character.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Character 表示游戏中的一个角色。
type Character struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                          // 唯一标识符
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                      // 角色名称
	Traits          []string               `protobuf:"bytes,3,rep,name=traits,proto3" json:"traits,omitempty"`                                                                  // 角色特征，例如：["Student", "Journalist"]
	CurrentLocation LocationType           `protobuf:"varint,4,opt,name=current_location,json=currentLocation,proto3,enum=game.LocationType" json:"current_location,omitempty"` // 当前所在位置
	Paranoia        int32                  `protobuf:"varint,5,opt,name=paranoia,proto3" json:"paranoia,omitempty"`                                                             // 妄想指数
	Goodwill        int32                  `protobuf:"varint,6,opt,name=goodwill,proto3" json:"goodwill,omitempty"`                                                             // 好感度
	Intrigue        int32                  `protobuf:"varint,7,opt,name=intrigue,proto3" json:"intrigue,omitempty"`                                                             // 阴谋标记
	IsAlive         bool                   `protobuf:"varint,8,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`                                                // 是否存活
	Abilities       []*Ability             `protobuf:"bytes,9,rep,name=abilities,proto3" json:"abilities,omitempty"`                                                            // 角色能力
	HiddenRole      PlayerRole             `protobuf:"varint,10,opt,name=hidden_role,json=hiddenRole,proto3,enum=game.PlayerRole" json:"hidden_role,omitempty"`                 // 角色的隐藏身份，对主角隐藏，仅供主谋查看
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_proto_game_character_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_character_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_proto_game_character_proto_rawDescGZIP(), []int{0}
}

func (x *Character) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetTraits() []string {
	if x != nil {
		return x.Traits
	}
	return nil
}

func (x *Character) GetCurrentLocation() LocationType {
	if x != nil {
		return x.CurrentLocation
	}
	return LocationType_LOCATION_TYPE_UNSPECIFIED
}

func (x *Character) GetParanoia() int32 {
	if x != nil {
		return x.Paranoia
	}
	return 0
}

func (x *Character) GetGoodwill() int32 {
	if x != nil {
		return x.Goodwill
	}
	return 0
}

func (x *Character) GetIntrigue() int32 {
	if x != nil {
		return x.Intrigue
	}
	return 0
}

func (x *Character) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *Character) GetAbilities() []*Ability {
	if x != nil {
		return x.Abilities
	}
	return nil
}

func (x *Character) GetHiddenRole() PlayerRole {
	if x != nil {
		return x.HiddenRole
	}
	return PlayerRole_PLAYER_ROLE_UNSPECIFIED
}

// CharacterConfig 定义特定剧本中角色的初始状态。
type CharacterConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CharacterId     string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`                                     // 引用基础角色定义
	InitialLocation LocationType           `protobuf:"varint,2,opt,name=initial_location,json=initialLocation,proto3,enum=game.LocationType" json:"initial_location,omitempty"` // 初始位置
	HiddenRole      PlayerRole             `protobuf:"varint,3,opt,name=hidden_role,json=hiddenRole,proto3,enum=game.PlayerRole" json:"hidden_role,omitempty"`                  // 此剧本中角色的秘密身份
	IsCulpritFor    string                 `protobuf:"bytes,4,opt,name=is_culprit_for,json=isCulpritFor,proto3" json:"is_culprit_for,omitempty"`                                // 如果此角色是特定悲剧的嫌疑犯
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CharacterConfig) Reset() {
	*x = CharacterConfig{}
	mi := &file_proto_game_character_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterConfig) ProtoMessage() {}

func (x *CharacterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_character_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterConfig.ProtoReflect.Descriptor instead.
func (*CharacterConfig) Descriptor() ([]byte, []int) {
	return file_proto_game_character_proto_rawDescGZIP(), []int{1}
}

func (x *CharacterConfig) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *CharacterConfig) GetInitialLocation() LocationType {
	if x != nil {
		return x.InitialLocation
	}
	return LocationType_LOCATION_TYPE_UNSPECIFIED
}

func (x *CharacterConfig) GetHiddenRole() PlayerRole {
	if x != nil {
		return x.HiddenRole
	}
	return PlayerRole_PLAYER_ROLE_UNSPECIFIED
}

func (x *CharacterConfig) GetIsCulpritFor() string {
	if x != nil {
		return x.IsCulpritFor
	}
	return ""
}

var File_proto_game_character_proto protoreflect.FileDescriptor

const file_proto_game_character_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/game/character.proto\x12\x04game\x1a\x19proto/game/location.proto\x1a\x18proto/game/ability.proto\x1a\x16proto/game/enums.proto\"\xd5\x02\n" +
	"\tCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06traits\x18\x03 \x03(\tR\x06traits\x12=\n" +
	"\x10current_location\x18\x04 \x01(\x0e2\x12.game.LocationTypeR\x0fcurrentLocation\x12\x1a\n" +
	"\bparanoia\x18\x05 \x01(\x05R\bparanoia\x12\x1a\n" +
	"\bgoodwill\x18\x06 \x01(\x05R\bgoodwill\x12\x1a\n" +
	"\bintrigue\x18\a \x01(\x05R\bintrigue\x12\x19\n" +
	"\bis_alive\x18\b \x01(\bR\aisAlive\x12+\n" +
	"\tabilities\x18\t \x03(\v2\r.game.AbilityR\tabilities\x121\n" +
	"\vhidden_role\x18\n" +
	" \x01(\x0e2\x10.game.PlayerRoleR\n" +
	"hiddenRole\"\xcc\x01\n" +
	"\x0fCharacterConfig\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12=\n" +
	"\x10initial_location\x18\x02 \x01(\x0e2\x12.game.LocationTypeR\x0finitialLocation\x121\n" +
	"\vhidden_role\x18\x03 \x01(\x0e2\x10.game.PlayerRoleR\n" +
	"hiddenRole\x12$\n" +
	"\x0eis_culprit_for\x18\x04 \x01(\tR\fisCulpritForB!Z\x1fgithub.com/user/repo/proto/gameb\x06proto3"

var (
	file_proto_game_character_proto_rawDescOnce sync.Once
	file_proto_game_character_proto_rawDescData []byte
)

func file_proto_game_character_proto_rawDescGZIP() []byte {
	file_proto_game_character_proto_rawDescOnce.Do(func() {
		file_proto_game_character_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_character_proto_rawDesc), len(file_proto_game_character_proto_rawDesc)))
	})
	return file_proto_game_character_proto_rawDescData
}

var file_proto_game_character_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_game_character_proto_goTypes = []any{
	(*Character)(nil),       // 0: game.Character
	(*CharacterConfig)(nil), // 1: game.CharacterConfig
	(LocationType)(0),       // 2: game.LocationType
	(*Ability)(nil),         // 3: game.Ability
	(PlayerRole)(0),         // 4: game.PlayerRole
}
var file_proto_game_character_proto_depIdxs = []int32{
	2, // 0: game.Character.current_location:type_name -> game.LocationType
	3, // 1: game.Character.abilities:type_name -> game.Ability
	4, // 2: game.Character.hidden_role:type_name -> game.PlayerRole
	2, // 3: game.CharacterConfig.initial_location:type_name -> game.LocationType
	4, // 4: game.CharacterConfig.hidden_role:type_name -> game.PlayerRole
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_game_character_proto_init() }
func file_proto_game_character_proto_init() {
	if File_proto_game_character_proto != nil {
		return
	}
	file_proto_game_location_proto_init()
	file_proto_game_ability_proto_init()
	file_proto_game_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_character_proto_rawDesc), len(file_proto_game_character_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_character_proto_goTypes,
		DependencyIndexes: file_proto_game_character_proto_depIdxs,
		MessageInfos:      file_proto_game_character_proto_msgTypes,
	}.Build()
	File_proto_game_character_proto = out.File
	file_proto_game_character_proto_goTypes = nil
	file_proto_game_character_proto_depIdxs = nil
}
