// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/game/tragedy.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TargetRuleType 定义悲剧如何选择目标角色。
type TargetRuleType int32

const (
	TargetRuleType_TARGET_RULE_TYPE_UNSPECIFIED               TargetRuleType = 0
	TargetRuleType_TARGET_RULE_TYPE_SPECIFIC_CHARACTER        TargetRuleType = 1 // 特定角色
	TargetRuleType_TARGET_RULE_TYPE_ANY_CHARACTER_AT_LOCATION TargetRuleType = 2 // 在某个地点的任何角色
)

// Enum value maps for TargetRuleType.
var (
	TargetRuleType_name = map[int32]string{
		0: "TARGET_RULE_TYPE_UNSPECIFIED",
		1: "TARGET_RULE_TYPE_SPECIFIC_CHARACTER",
		2: "TARGET_RULE_TYPE_ANY_CHARACTER_AT_LOCATION",
	}
	TargetRuleType_value = map[string]int32{
		"TARGET_RULE_TYPE_UNSPECIFIED":               0,
		"TARGET_RULE_TYPE_SPECIFIC_CHARACTER":        1,
		"TARGET_RULE_TYPE_ANY_CHARACTER_AT_LOCATION": 2,
	}
)

func (x TargetRuleType) Enum() *TargetRuleType {
	p := new(TargetRuleType)
	*p = x
	return p
}

func (x TargetRuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetRuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_tragedy_proto_enumTypes[0].Descriptor()
}

func (TargetRuleType) Type() protoreflect.EnumType {
	return &file_proto_game_tragedy_proto_enumTypes[0]
}

func (x TargetRuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetRuleType.Descriptor instead.
func (TargetRuleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_tragedy_proto_rawDescGZIP(), []int{0}
}

// TragedyCondition 定义悲剧发生的条件。
type TragedyCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TragedyType   string                 `protobuf:"bytes,1,opt,name=tragedy_type,json=tragedyType,proto3" json:"tragedy_type,omitempty"`                        // 悲剧类型
	Day           int32                  `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`                                                          // 悲剧可能发生的日期
	CulpritId     string                 `protobuf:"bytes,3,opt,name=culprit_id,json=culpritId,proto3" json:"culprit_id,omitempty"`                              // 嫌疑人ID
	Conditions    []*Condition           `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty"`                                             // 必须满足的条件列表
	TargetRule    TargetRuleType         `protobuf:"varint,5,opt,name=target_rule,json=targetRule,proto3,enum=game.TargetRuleType" json:"target_rule,omitempty"` // 目标规则
	Abilities     []*Ability             `protobuf:"bytes,6,rep,name=abilities,proto3" json:"abilities,omitempty"`                                               // 悲剧发生时触发的能力
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`                                // 运行时状态：此悲剧当前是否在剧本中活跃？
	IsPrevented   bool                   `protobuf:"varint,8,opt,name=is_prevented,json=isPrevented,proto3" json:"is_prevented,omitempty"`                       // 运行时状态：此悲剧是否已被阻止？
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TragedyCondition) Reset() {
	*x = TragedyCondition{}
	mi := &file_proto_game_tragedy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TragedyCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TragedyCondition) ProtoMessage() {}

func (x *TragedyCondition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_tragedy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TragedyCondition.ProtoReflect.Descriptor instead.
func (*TragedyCondition) Descriptor() ([]byte, []int) {
	return file_proto_game_tragedy_proto_rawDescGZIP(), []int{0}
}

func (x *TragedyCondition) GetTragedyType() string {
	if x != nil {
		return x.TragedyType
	}
	return ""
}

func (x *TragedyCondition) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *TragedyCondition) GetCulpritId() string {
	if x != nil {
		return x.CulpritId
	}
	return ""
}

func (x *TragedyCondition) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *TragedyCondition) GetTargetRule() TargetRuleType {
	if x != nil {
		return x.TargetRule
	}
	return TargetRuleType_TARGET_RULE_TYPE_UNSPECIFIED
}

func (x *TragedyCondition) GetAbilities() []*Ability {
	if x != nil {
		return x.Abilities
	}
	return nil
}

func (x *TragedyCondition) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *TragedyCondition) GetIsPrevented() bool {
	if x != nil {
		return x.IsPrevented
	}
	return false
}

// Condition 定义悲剧的一个单一条件。
type Condition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`  // 角色ID
	Location      LocationType           `protobuf:"varint,2,opt,name=location,proto3,enum=game.LocationType" json:"location,omitempty"`   // 所在位置
	MinParanoia   int32                  `protobuf:"varint,3,opt,name=min_paranoia,json=minParanoia,proto3" json:"min_paranoia,omitempty"` // 最小妄想指数
	IsAlone       bool                   `protobuf:"varint,4,opt,name=is_alone,json=isAlone,proto3" json:"is_alone,omitempty"`             // 是否独处
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_proto_game_tragedy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_tragedy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_proto_game_tragedy_proto_rawDescGZIP(), []int{1}
}

func (x *Condition) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *Condition) GetLocation() LocationType {
	if x != nil {
		return x.Location
	}
	return LocationType_LOCATION_TYPE_UNSPECIFIED
}

func (x *Condition) GetMinParanoia() int32 {
	if x != nil {
		return x.MinParanoia
	}
	return 0
}

func (x *Condition) GetIsAlone() bool {
	if x != nil {
		return x.IsAlone
	}
	return false
}

var File_proto_game_tragedy_proto protoreflect.FileDescriptor

const file_proto_game_tragedy_proto_rawDesc = "" +
	"\n" +
	"\x18proto/game/tragedy.proto\x12\x04game\x1a\x18proto/game/ability.proto\x1a\x19proto/game/location.proto\"\xbb\x02\n" +
	"\x10TragedyCondition\x12!\n" +
	"\ftragedy_type\x18\x01 \x01(\tR\vtragedyType\x12\x10\n" +
	"\x03day\x18\x02 \x01(\x05R\x03day\x12\x1d\n" +
	"\n" +
	"culprit_id\x18\x03 \x01(\tR\tculpritId\x12/\n" +
	"\n" +
	"conditions\x18\x04 \x03(\v2\x0f.game.ConditionR\n" +
	"conditions\x125\n" +
	"\vtarget_rule\x18\x05 \x01(\x0e2\x14.game.TargetRuleTypeR\n" +
	"targetRule\x12+\n" +
	"\tabilities\x18\x06 \x03(\v2\r.game.AbilityR\tabilities\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12!\n" +
	"\fis_prevented\x18\b \x01(\bR\visPrevented\"\x9c\x01\n" +
	"\tCondition\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12.\n" +
	"\blocation\x18\x02 \x01(\x0e2\x12.game.LocationTypeR\blocation\x12!\n" +
	"\fmin_paranoia\x18\x03 \x01(\x05R\vminParanoia\x12\x19\n" +
	"\bis_alone\x18\x04 \x01(\bR\aisAlone*\x8b\x01\n" +
	"\x0eTargetRuleType\x12 \n" +
	"\x1cTARGET_RULE_TYPE_UNSPECIFIED\x10\x00\x12'\n" +
	"#TARGET_RULE_TYPE_SPECIFIC_CHARACTER\x10\x01\x12.\n" +
	"*TARGET_RULE_TYPE_ANY_CHARACTER_AT_LOCATION\x10\x02B!Z\x1fgithub.com/user/repo/proto/gameb\x06proto3"

var (
	file_proto_game_tragedy_proto_rawDescOnce sync.Once
	file_proto_game_tragedy_proto_rawDescData []byte
)

func file_proto_game_tragedy_proto_rawDescGZIP() []byte {
	file_proto_game_tragedy_proto_rawDescOnce.Do(func() {
		file_proto_game_tragedy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_tragedy_proto_rawDesc), len(file_proto_game_tragedy_proto_rawDesc)))
	})
	return file_proto_game_tragedy_proto_rawDescData
}

var file_proto_game_tragedy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_game_tragedy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_game_tragedy_proto_goTypes = []any{
	(TargetRuleType)(0),      // 0: game.TargetRuleType
	(*TragedyCondition)(nil), // 1: game.TragedyCondition
	(*Condition)(nil),        // 2: game.Condition
	(*Ability)(nil),          // 3: game.Ability
	(LocationType)(0),        // 4: game.LocationType
}
var file_proto_game_tragedy_proto_depIdxs = []int32{
	2, // 0: game.TragedyCondition.conditions:type_name -> game.Condition
	0, // 1: game.TragedyCondition.target_rule:type_name -> game.TargetRuleType
	3, // 2: game.TragedyCondition.abilities:type_name -> game.Ability
	4, // 3: game.Condition.location:type_name -> game.LocationType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_game_tragedy_proto_init() }
func file_proto_game_tragedy_proto_init() {
	if File_proto_game_tragedy_proto != nil {
		return
	}
	file_proto_game_ability_proto_init()
	file_proto_game_location_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_tragedy_proto_rawDesc), len(file_proto_game_tragedy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_tragedy_proto_goTypes,
		DependencyIndexes: file_proto_game_tragedy_proto_depIdxs,
		EnumInfos:         file_proto_game_tragedy_proto_enumTypes,
		MessageInfos:      file_proto_game_tragedy_proto_msgTypes,
	}.Build()
	File_proto_game_tragedy_proto = out.File
	file_proto_game_tragedy_proto_goTypes = nil
	file_proto_game_tragedy_proto_depIdxs = nil
}
