// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/condition.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatCondition_StatType int32

const (
	StatCondition_STAT_TYPE_UNSPECIFIED StatCondition_StatType = 0 // 未指定
	StatCondition_PARANOIA_STAT         StatCondition_StatType = 1 // 妄想值
	StatCondition_GOODWILL_STAT         StatCondition_StatType = 2 // 好感值
	StatCondition_INTRIGUE_STAT         StatCondition_StatType = 3 // 阴谋值
)

// Enum value maps for StatCondition_StatType.
var (
	StatCondition_StatType_name = map[int32]string{
		0: "STAT_TYPE_UNSPECIFIED",
		1: "PARANOIA_STAT",
		2: "GOODWILL_STAT",
		3: "INTRIGUE_STAT",
	}
	StatCondition_StatType_value = map[string]int32{
		"STAT_TYPE_UNSPECIFIED": 0,
		"PARANOIA_STAT":         1,
		"GOODWILL_STAT":         2,
		"INTRIGUE_STAT":         3,
	}
)

func (x StatCondition_StatType) Enum() *StatCondition_StatType {
	p := new(StatCondition_StatType)
	*p = x
	return p
}

func (x StatCondition_StatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatCondition_StatType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_condition_proto_enumTypes[0].Descriptor()
}

func (StatCondition_StatType) Type() protoreflect.EnumType {
	return &file_v1_condition_proto_enumTypes[0]
}

func (x StatCondition_StatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatCondition_StatType.Descriptor instead.
func (StatCondition_StatType) EnumDescriptor() ([]byte, []int) {
	return file_v1_condition_proto_rawDescGZIP(), []int{1, 0}
}

type StatCondition_Comparator int32

const (
	StatCondition_COMPARATOR_UNSPECIFIED StatCondition_Comparator = 0 // 未指定
	StatCondition_GREATER_THAN           StatCondition_Comparator = 1 // 大于
	StatCondition_LESS_THAN              StatCondition_Comparator = 2 // 小于
	StatCondition_EQUAL_TO               StatCondition_Comparator = 3 // 等于
	StatCondition_GREATER_THAN_OR_EQUAL  StatCondition_Comparator = 4 // 大于等于
	StatCondition_LESS_THAN_OR_EQUAL     StatCondition_Comparator = 5 // 小于等于
)

// Enum value maps for StatCondition_Comparator.
var (
	StatCondition_Comparator_name = map[int32]string{
		0: "COMPARATOR_UNSPECIFIED",
		1: "GREATER_THAN",
		2: "LESS_THAN",
		3: "EQUAL_TO",
		4: "GREATER_THAN_OR_EQUAL",
		5: "LESS_THAN_OR_EQUAL",
	}
	StatCondition_Comparator_value = map[string]int32{
		"COMPARATOR_UNSPECIFIED": 0,
		"GREATER_THAN":           1,
		"LESS_THAN":              2,
		"EQUAL_TO":               3,
		"GREATER_THAN_OR_EQUAL":  4,
		"LESS_THAN_OR_EQUAL":     5,
	}
)

func (x StatCondition_Comparator) Enum() *StatCondition_Comparator {
	p := new(StatCondition_Comparator)
	*p = x
	return p
}

func (x StatCondition_Comparator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatCondition_Comparator) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_condition_proto_enumTypes[1].Descriptor()
}

func (StatCondition_Comparator) Type() protoreflect.EnumType {
	return &file_v1_condition_proto_enumTypes[1]
}

func (x StatCondition_Comparator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatCondition_Comparator.Descriptor instead.
func (StatCondition_Comparator) EnumDescriptor() ([]byte, []int) {
	return file_v1_condition_proto_rawDescGZIP(), []int{1, 1}
}

// 条件的通用消息，使用 oneof 包含各种具体条件
type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ConditionType:
	//
	//	*Condition_StatCondition
	//	*Condition_LocationCondition
	ConditionType isCondition_ConditionType `protobuf_oneof:"condition_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_v1_condition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_v1_condition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_v1_condition_proto_rawDescGZIP(), []int{0}
}

func (x *Condition) GetConditionType() isCondition_ConditionType {
	if x != nil {
		return x.ConditionType
	}
	return nil
}

func (x *Condition) GetStatCondition() *StatCondition {
	if x != nil {
		if x, ok := x.ConditionType.(*Condition_StatCondition); ok {
			return x.StatCondition
		}
	}
	return nil
}

func (x *Condition) GetLocationCondition() *LocationCondition {
	if x != nil {
		if x, ok := x.ConditionType.(*Condition_LocationCondition); ok {
			return x.LocationCondition
		}
	}
	return nil
}

type isCondition_ConditionType interface {
	isCondition_ConditionType()
}

type Condition_StatCondition struct {
	StatCondition *StatCondition `protobuf:"bytes,1,opt,name=stat_condition,json=statCondition,proto3,oneof"` // 属性条件（例如，妄想值达到某阈值）
}

type Condition_LocationCondition struct {
	LocationCondition *LocationCondition `protobuf:"bytes,2,opt,name=location_condition,json=locationCondition,proto3,oneof"` // 地点条件（例如，角色在特定地点）
}

func (*Condition_StatCondition) isCondition_ConditionType() {}

func (*Condition_LocationCondition) isCondition_ConditionType() {}

// 属性条件
type StatCondition struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	CharacterId   int32                    `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`                       // 目标角色ID
	StatType      StatCondition_StatType   `protobuf:"varint,2,opt,name=stat_type,json=statType,proto3,enum=v1.StatCondition_StatType" json:"stat_type,omitempty"` // 要检查的属性类型
	Comparator    StatCondition_Comparator `protobuf:"varint,3,opt,name=comparator,proto3,enum=v1.StatCondition_Comparator" json:"comparator,omitempty"`           // 比较符
	Value         int32                    `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`                                                      // 比较的值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatCondition) Reset() {
	*x = StatCondition{}
	mi := &file_v1_condition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatCondition) ProtoMessage() {}

func (x *StatCondition) ProtoReflect() protoreflect.Message {
	mi := &file_v1_condition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatCondition.ProtoReflect.Descriptor instead.
func (*StatCondition) Descriptor() ([]byte, []int) {
	return file_v1_condition_proto_rawDescGZIP(), []int{1}
}

func (x *StatCondition) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *StatCondition) GetStatType() StatCondition_StatType {
	if x != nil {
		return x.StatType
	}
	return StatCondition_STAT_TYPE_UNSPECIFIED
}

func (x *StatCondition) GetComparator() StatCondition_Comparator {
	if x != nil {
		return x.Comparator
	}
	return StatCondition_COMPARATOR_UNSPECIFIED
}

func (x *StatCondition) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 地点条件
type LocationCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int32                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // 目标角色ID
	Location      LocationType           `protobuf:"varint,2,opt,name=location,proto3,enum=v1.LocationType" json:"location,omitempty"`     // 目标地点
	IsAlone       bool                   `protobuf:"varint,3,opt,name=is_alone,json=isAlone,proto3" json:"is_alone,omitempty"`             // 是否在该地点独处
	NotAlone      bool                   `protobuf:"varint,4,opt,name=not_alone,json=notAlone,proto3" json:"not_alone,omitempty"`          // 是否在该地点不独处
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationCondition) Reset() {
	*x = LocationCondition{}
	mi := &file_v1_condition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationCondition) ProtoMessage() {}

func (x *LocationCondition) ProtoReflect() protoreflect.Message {
	mi := &file_v1_condition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationCondition.ProtoReflect.Descriptor instead.
func (*LocationCondition) Descriptor() ([]byte, []int) {
	return file_v1_condition_proto_rawDescGZIP(), []int{2}
}

func (x *LocationCondition) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *LocationCondition) GetLocation() LocationType {
	if x != nil {
		return x.Location
	}
	return LocationType_LOCATION_TYPE_UNSPECIFIED
}

func (x *LocationCondition) GetIsAlone() bool {
	if x != nil {
		return x.IsAlone
	}
	return false
}

func (x *LocationCondition) GetNotAlone() bool {
	if x != nil {
		return x.NotAlone
	}
	return false
}

var File_v1_condition_proto protoreflect.FileDescriptor

const file_v1_condition_proto_rawDesc = "" +
	"\n" +
	"\x12v1/condition.proto\x12\x02v1\x1a\x0ev1/enums.proto\"\xa1\x01\n" +
	"\tCondition\x12:\n" +
	"\x0estat_condition\x18\x01 \x01(\v2\x11.v1.StatConditionH\x00R\rstatCondition\x12F\n" +
	"\x12location_condition\x18\x02 \x01(\v2\x15.v1.LocationConditionH\x00R\x11locationConditionB\x10\n" +
	"\x0econdition_type\"\xac\x03\n" +
	"\rStatCondition\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x05R\vcharacterId\x127\n" +
	"\tstat_type\x18\x02 \x01(\x0e2\x1a.v1.StatCondition.StatTypeR\bstatType\x12<\n" +
	"\n" +
	"comparator\x18\x03 \x01(\x0e2\x1c.v1.StatCondition.ComparatorR\n" +
	"comparator\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x05R\x05value\"^\n" +
	"\bStatType\x12\x19\n" +
	"\x15STAT_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPARANOIA_STAT\x10\x01\x12\x11\n" +
	"\rGOODWILL_STAT\x10\x02\x12\x11\n" +
	"\rINTRIGUE_STAT\x10\x03\"\x8a\x01\n" +
	"\n" +
	"Comparator\x12\x1a\n" +
	"\x16COMPARATOR_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fGREATER_THAN\x10\x01\x12\r\n" +
	"\tLESS_THAN\x10\x02\x12\f\n" +
	"\bEQUAL_TO\x10\x03\x12\x19\n" +
	"\x15GREATER_THAN_OR_EQUAL\x10\x04\x12\x16\n" +
	"\x12LESS_THAN_OR_EQUAL\x10\x05\"\x9c\x01\n" +
	"\x11LocationCondition\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x05R\vcharacterId\x12,\n" +
	"\blocation\x18\x02 \x01(\x0e2\x10.v1.LocationTypeR\blocation\x12\x19\n" +
	"\bis_alone\x18\x03 \x01(\bR\aisAlone\x12\x1b\n" +
	"\tnot_alone\x18\x04 \x01(\bR\bnotAloneB)Z'tragedylooper/internal/game/proto/v1;v1b\x06proto3"

var (
	file_v1_condition_proto_rawDescOnce sync.Once
	file_v1_condition_proto_rawDescData []byte
)

func file_v1_condition_proto_rawDescGZIP() []byte {
	file_v1_condition_proto_rawDescOnce.Do(func() {
		file_v1_condition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_condition_proto_rawDesc), len(file_v1_condition_proto_rawDesc)))
	})
	return file_v1_condition_proto_rawDescData
}

var file_v1_condition_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_condition_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_condition_proto_goTypes = []any{
	(StatCondition_StatType)(0),   // 0: v1.StatCondition.StatType
	(StatCondition_Comparator)(0), // 1: v1.StatCondition.Comparator
	(*Condition)(nil),             // 2: v1.Condition
	(*StatCondition)(nil),         // 3: v1.StatCondition
	(*LocationCondition)(nil),     // 4: v1.LocationCondition
	(LocationType)(0),             // 5: v1.LocationType
}
var file_v1_condition_proto_depIdxs = []int32{
	3, // 0: v1.Condition.stat_condition:type_name -> v1.StatCondition
	4, // 1: v1.Condition.location_condition:type_name -> v1.LocationCondition
	0, // 2: v1.StatCondition.stat_type:type_name -> v1.StatCondition.StatType
	1, // 3: v1.StatCondition.comparator:type_name -> v1.StatCondition.Comparator
	5, // 4: v1.LocationCondition.location:type_name -> v1.LocationType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_condition_proto_init() }
func file_v1_condition_proto_init() {
	if File_v1_condition_proto != nil {
		return
	}
	file_v1_enums_proto_init()
	file_v1_condition_proto_msgTypes[0].OneofWrappers = []any{
		(*Condition_StatCondition)(nil),
		(*Condition_LocationCondition)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_condition_proto_rawDesc), len(file_v1_condition_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_condition_proto_goTypes,
		DependencyIndexes: file_v1_condition_proto_depIdxs,
		EnumInfos:         file_v1_condition_proto_enumTypes,
		MessageInfos:      file_v1_condition_proto_msgTypes,
	}.Build()
	File_v1_condition_proto = out.File
	file_v1_condition_proto_goTypes = nil
	file_v1_condition_proto_depIdxs = nil
}
