// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/v1/enums.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CardType 定义玩家可以打出的卡牌类型。
type CardType int32

const (
	CardType_CARD_TYPE_UNSPECIFIED CardType = 0
	CardType_CARD_TYPE_MOVEMENT    CardType = 1 // 移动
	CardType_CARD_TYPE_PARANOIA    CardType = 2 // 妄想
	CardType_CARD_TYPE_GOODWILL    CardType = 3 // 好感
	CardType_CARD_TYPE_INTRIGUE    CardType = 4 // 阴谋
	CardType_CARD_TYPE_SPECIAL     CardType = 5 // 用于特殊卡牌效果
)

// Enum value maps for CardType.
var (
	CardType_name = map[int32]string{
		0: "CARD_TYPE_UNSPECIFIED",
		1: "CARD_TYPE_MOVEMENT",
		2: "CARD_TYPE_PARANOIA",
		3: "CARD_TYPE_GOODWILL",
		4: "CARD_TYPE_INTRIGUE",
		5: "CARD_TYPE_SPECIAL",
	}
	CardType_value = map[string]int32{
		"CARD_TYPE_UNSPECIFIED": 0,
		"CARD_TYPE_MOVEMENT":    1,
		"CARD_TYPE_PARANOIA":    2,
		"CARD_TYPE_GOODWILL":    3,
		"CARD_TYPE_INTRIGUE":    4,
		"CARD_TYPE_SPECIAL":     5,
	}
)

func (x CardType) Enum() *CardType {
	p := new(CardType)
	*p = x
	return p
}

func (x CardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_enums_proto_enumTypes[0].Descriptor()
}

func (CardType) Type() protoreflect.EnumType {
	return &file_proto_v1_enums_proto_enumTypes[0]
}

func (x CardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardType.Descriptor instead.
func (CardType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_enums_proto_rawDescGZIP(), []int{0}
}

// PlayerRole 定义连接玩家的角色（人类或 LLM）。
type PlayerRole int32

const (
	PlayerRole_PLAYER_ROLE_UNSPECIFIED PlayerRole = 0
	PlayerRole_PLAYER_ROLE_MASTERMIND  PlayerRole = 1 // 主谋
	PlayerRole_PLAYER_ROLE_PROTAGONIST PlayerRole = 2 // 主角
)

// Enum value maps for PlayerRole.
var (
	PlayerRole_name = map[int32]string{
		0: "PLAYER_ROLE_UNSPECIFIED",
		1: "PLAYER_ROLE_MASTERMIND",
		2: "PLAYER_ROLE_PROTAGONIST",
	}
	PlayerRole_value = map[string]int32{
		"PLAYER_ROLE_UNSPECIFIED": 0,
		"PLAYER_ROLE_MASTERMIND":  1,
		"PLAYER_ROLE_PROTAGONIST": 2,
	}
)

func (x PlayerRole) Enum() *PlayerRole {
	p := new(PlayerRole)
	*p = x
	return p
}

func (x PlayerRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_enums_proto_enumTypes[1].Descriptor()
}

func (PlayerRole) Type() protoreflect.EnumType {
	return &file_proto_v1_enums_proto_enumTypes[1]
}

func (x PlayerRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerRole.Descriptor instead.
func (PlayerRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_enums_proto_rawDescGZIP(), []int{1}
}

// GamePhase 定义游戏日期的当前阶段。
type GamePhase int32

const (
	GamePhase_GAME_PHASE_UNSPECIFIED       GamePhase = 0
	GamePhase_GAME_PHASE_MORNING           GamePhase = 1  // 早晨
	GamePhase_GAME_PHASE_CARD_PLAY         GamePhase = 2  // 出牌阶段
	GamePhase_GAME_PHASE_CARD_REVEAL       GamePhase = 3  // 牌揭示阶段
	GamePhase_GAME_PHASE_CARD_RESOLVE      GamePhase = 4  // 牌结算阶段
	GamePhase_GAME_PHASE_ABILITIES         GamePhase = 5  // 能力阶段
	GamePhase_GAME_PHASE_INCIDENTS         GamePhase = 6  // 事件阶段
	GamePhase_GAME_PHASE_DAY_END           GamePhase = 7  // 天结束
	GamePhase_GAME_PHASE_LOOP_END          GamePhase = 8  // 循环结束
	GamePhase_GAME_PHASE_GAME_OVER         GamePhase = 9  // 游戏结束
	GamePhase_GAME_PHASE_PROTAGONIST_GUESS GamePhase = 10 // 最终猜测阶段
)

// Enum value maps for GamePhase.
var (
	GamePhase_name = map[int32]string{
		0:  "GAME_PHASE_UNSPECIFIED",
		1:  "GAME_PHASE_MORNING",
		2:  "GAME_PHASE_CARD_PLAY",
		3:  "GAME_PHASE_CARD_REVEAL",
		4:  "GAME_PHASE_CARD_RESOLVE",
		5:  "GAME_PHASE_ABILITIES",
		6:  "GAME_PHASE_INCIDENTS",
		7:  "GAME_PHASE_DAY_END",
		8:  "GAME_PHASE_LOOP_END",
		9:  "GAME_PHASE_GAME_OVER",
		10: "GAME_PHASE_PROTAGONIST_GUESS",
	}
	GamePhase_value = map[string]int32{
		"GAME_PHASE_UNSPECIFIED":       0,
		"GAME_PHASE_MORNING":           1,
		"GAME_PHASE_CARD_PLAY":         2,
		"GAME_PHASE_CARD_REVEAL":       3,
		"GAME_PHASE_CARD_RESOLVE":      4,
		"GAME_PHASE_ABILITIES":         5,
		"GAME_PHASE_INCIDENTS":         6,
		"GAME_PHASE_DAY_END":           7,
		"GAME_PHASE_LOOP_END":          8,
		"GAME_PHASE_GAME_OVER":         9,
		"GAME_PHASE_PROTAGONIST_GUESS": 10,
	}
)

func (x GamePhase) Enum() *GamePhase {
	p := new(GamePhase)
	*p = x
	return p
}

func (x GamePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GamePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_enums_proto_enumTypes[2].Descriptor()
}

func (GamePhase) Type() protoreflect.EnumType {
	return &file_proto_v1_enums_proto_enumTypes[2]
}

func (x GamePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GamePhase.Descriptor instead.
func (GamePhase) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_enums_proto_rawDescGZIP(), []int{2}
}

// GameEventType for GameEvent
type GameEventType int32

const (
	GameEventType_GAME_EVENT_TYPE_UNSPECIFIED        GameEventType = 0
	GameEventType_GAME_EVENT_TYPE_CARD_PLAYED        GameEventType = 1  // 打出卡牌
	GameEventType_GAME_EVENT_TYPE_CHARACTER_MOVED    GameEventType = 2  // 角色移动
	GameEventType_GAME_EVENT_TYPE_PARANOIA_ADJUSTED  GameEventType = 3  // 妄想调整
	GameEventType_GAME_EVENT_TYPE_GOODWILL_ADJUSTED  GameEventType = 4  // 好感调整
	GameEventType_GAME_EVENT_TYPE_INTRIGUE_ADJUSTED  GameEventType = 5  // 阴谋调整
	GameEventType_GAME_EVENT_TYPE_ABILITY_USED       GameEventType = 6  // 使用能力
	GameEventType_GAME_EVENT_TYPE_TRAGEDY_TRIGGERED  GameEventType = 7  // 悲剧触发
	GameEventType_GAME_EVENT_TYPE_TRAGEDY_PREVENTED  GameEventType = 8  // 悲剧阻止
	GameEventType_GAME_EVENT_TYPE_DAY_ADVANCED       GameEventType = 9  // 天数推进
	GameEventType_GAME_EVENT_TYPE_LOOP_RESET         GameEventType = 10 // 循环重置
	GameEventType_GAME_EVENT_TYPE_GAME_OVER          GameEventType = 11 // 游戏结束
	GameEventType_GAME_EVENT_TYPE_PLAYER_GUESS       GameEventType = 12 // 玩家猜测
	GameEventType_GAME_EVENT_TYPE_CHOICE_REQUIRED    GameEventType = 13 // 需要玩家选择
	GameEventType_GAME_EVENT_TYPE_INCIDENT_TRIGGERED GameEventType = 14 // 事件触发
)

// Enum value maps for GameEventType.
var (
	GameEventType_name = map[int32]string{
		0:  "GAME_EVENT_TYPE_UNSPECIFIED",
		1:  "GAME_EVENT_TYPE_CARD_PLAYED",
		2:  "GAME_EVENT_TYPE_CHARACTER_MOVED",
		3:  "GAME_EVENT_TYPE_PARANOIA_ADJUSTED",
		4:  "GAME_EVENT_TYPE_GOODWILL_ADJUSTED",
		5:  "GAME_EVENT_TYPE_INTRIGUE_ADJUSTED",
		6:  "GAME_EVENT_TYPE_ABILITY_USED",
		7:  "GAME_EVENT_TYPE_TRAGEDY_TRIGGERED",
		8:  "GAME_EVENT_TYPE_TRAGEDY_PREVENTED",
		9:  "GAME_EVENT_TYPE_DAY_ADVANCED",
		10: "GAME_EVENT_TYPE_LOOP_RESET",
		11: "GAME_EVENT_TYPE_GAME_OVER",
		12: "GAME_EVENT_TYPE_PLAYER_GUESS",
		13: "GAME_EVENT_TYPE_CHOICE_REQUIRED",
		14: "GAME_EVENT_TYPE_INCIDENT_TRIGGERED",
	}
	GameEventType_value = map[string]int32{
		"GAME_EVENT_TYPE_UNSPECIFIED":        0,
		"GAME_EVENT_TYPE_CARD_PLAYED":        1,
		"GAME_EVENT_TYPE_CHARACTER_MOVED":    2,
		"GAME_EVENT_TYPE_PARANOIA_ADJUSTED":  3,
		"GAME_EVENT_TYPE_GOODWILL_ADJUSTED":  4,
		"GAME_EVENT_TYPE_INTRIGUE_ADJUSTED":  5,
		"GAME_EVENT_TYPE_ABILITY_USED":       6,
		"GAME_EVENT_TYPE_TRAGEDY_TRIGGERED":  7,
		"GAME_EVENT_TYPE_TRAGEDY_PREVENTED":  8,
		"GAME_EVENT_TYPE_DAY_ADVANCED":       9,
		"GAME_EVENT_TYPE_LOOP_RESET":         10,
		"GAME_EVENT_TYPE_GAME_OVER":          11,
		"GAME_EVENT_TYPE_PLAYER_GUESS":       12,
		"GAME_EVENT_TYPE_CHOICE_REQUIRED":    13,
		"GAME_EVENT_TYPE_INCIDENT_TRIGGERED": 14,
	}
)

func (x GameEventType) Enum() *GameEventType {
	p := new(GameEventType)
	*p = x
	return p
}

func (x GameEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_enums_proto_enumTypes[3].Descriptor()
}

func (GameEventType) Type() protoreflect.EnumType {
	return &file_proto_v1_enums_proto_enumTypes[3]
}

func (x GameEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameEventType.Descriptor instead.
func (GameEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_enums_proto_rawDescGZIP(), []int{3}
}

// ActionType 定义了玩家可以执行的操作类型。
type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED          ActionType = 0
	ActionType_ACTION_TYPE_PLAY_CARD            ActionType = 1 // 出牌
	ActionType_ACTION_TYPE_USE_ABILITY          ActionType = 2 // 使用能力
	ActionType_ACTION_TYPE_MAKE_GUESS           ActionType = 3 // 作出猜测
	ActionType_ACTION_TYPE_READY_FOR_NEXT_PHASE ActionType = 4 // 准备好进入下一阶段
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ACTION_TYPE_PLAY_CARD",
		2: "ACTION_TYPE_USE_ABILITY",
		3: "ACTION_TYPE_MAKE_GUESS",
		4: "ACTION_TYPE_READY_FOR_NEXT_PHASE",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED":          0,
		"ACTION_TYPE_PLAY_CARD":            1,
		"ACTION_TYPE_USE_ABILITY":          2,
		"ACTION_TYPE_MAKE_GUESS":           3,
		"ACTION_TYPE_READY_FOR_NEXT_PHASE": 4,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_enums_proto_enumTypes[4].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_proto_v1_enums_proto_enumTypes[4]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_enums_proto_rawDescGZIP(), []int{4}
}

// RoleType 定义了玩家在游戏中的具体角色。
type RoleType int32

const (
	RoleType_ROLE_TYPE_UNSPECIFIED         RoleType = 0 // 未指定角色类型 (默认值)
	RoleType_ROLE_TYPE_INNOCENT            RoleType = 1 // 无辜者
	RoleType_ROLE_TYPE_KILLER              RoleType = 2 // 杀手
	RoleType_ROLE_TYPE_BRAIN               RoleType = 3 // 大脑
	RoleType_ROLE_TYPE_KEY_PERSON          RoleType = 4 // 关键人物
	RoleType_ROLE_TYPE_FRIEND              RoleType = 5 // 朋友
	RoleType_ROLE_TYPE_CONSPIRACY_THEORIST RoleType = 6 // 阴谋论者
	RoleType_ROLE_TYPE_CULTIST             RoleType = 7 // 例如：具有善意拒绝的角色
	// 注意：Mastermind 和 Protagonist 也可以在 PlayerRole 中定义，这里是作为游戏内具体角色的一种。
	RoleType_ROLE_TYPE_MASTERMIND  RoleType = 8 // LLM 玩家角色 (主谋)
	RoleType_ROLE_TYPE_PROTAGONIST RoleType = 9 // LLM 玩家角色 (主角)
)

// Enum value maps for RoleType.
var (
	RoleType_name = map[int32]string{
		0: "ROLE_TYPE_UNSPECIFIED",
		1: "ROLE_TYPE_INNOCENT",
		2: "ROLE_TYPE_KILLER",
		3: "ROLE_TYPE_BRAIN",
		4: "ROLE_TYPE_KEY_PERSON",
		5: "ROLE_TYPE_FRIEND",
		6: "ROLE_TYPE_CONSPIRACY_THEORIST",
		7: "ROLE_TYPE_CULTIST",
		8: "ROLE_TYPE_MASTERMIND",
		9: "ROLE_TYPE_PROTAGONIST",
	}
	RoleType_value = map[string]int32{
		"ROLE_TYPE_UNSPECIFIED":         0,
		"ROLE_TYPE_INNOCENT":            1,
		"ROLE_TYPE_KILLER":              2,
		"ROLE_TYPE_BRAIN":               3,
		"ROLE_TYPE_KEY_PERSON":          4,
		"ROLE_TYPE_FRIEND":              5,
		"ROLE_TYPE_CONSPIRACY_THEORIST": 6,
		"ROLE_TYPE_CULTIST":             7,
		"ROLE_TYPE_MASTERMIND":          8,
		"ROLE_TYPE_PROTAGONIST":         9,
	}
)

func (x RoleType) Enum() *RoleType {
	p := new(RoleType)
	*p = x
	return p
}

func (x RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_enums_proto_enumTypes[5].Descriptor()
}

func (RoleType) Type() protoreflect.EnumType {
	return &file_proto_v1_enums_proto_enumTypes[5]
}

func (x RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleType.Descriptor instead.
func (RoleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_enums_proto_rawDescGZIP(), []int{5}
}

// TragedyType 定义了剧本中可能发生的悲剧类型。
// TragedyType 定义了在游戏中可能发生的悲剧类型。
type TragedyType int32

const (
	TragedyType_TRAGEDY_TYPE_UNSPECIFIED TragedyType = 0 // 未指定悲剧类型 (默认值)
	TragedyType_TRAGEDY_TYPE_MURDER      TragedyType = 1 // 谋杀
	TragedyType_TRAGEDY_TYPE_SUICIDE     TragedyType = 2 // 自杀
	TragedyType_TRAGEDY_TYPE_SEALED      TragedyType = 3 // 例如：封印物品剧情
)

// Enum value maps for TragedyType.
var (
	TragedyType_name = map[int32]string{
		0: "TRAGEDY_TYPE_UNSPECIFIED",
		1: "TRAGEDY_TYPE_MURDER",
		2: "TRAGEDY_TYPE_SUICIDE",
		3: "TRAGEDY_TYPE_SEALED",
	}
	TragedyType_value = map[string]int32{
		"TRAGEDY_TYPE_UNSPECIFIED": 0,
		"TRAGEDY_TYPE_MURDER":      1,
		"TRAGEDY_TYPE_SUICIDE":     2,
		"TRAGEDY_TYPE_SEALED":      3,
	}
)

func (x TragedyType) Enum() *TragedyType {
	p := new(TragedyType)
	*p = x
	return p
}

func (x TragedyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TragedyType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_enums_proto_enumTypes[6].Descriptor()
}

func (TragedyType) Type() protoreflect.EnumType {
	return &file_proto_v1_enums_proto_enumTypes[6]
}

func (x TragedyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TragedyType.Descriptor instead.
func (TragedyType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_enums_proto_rawDescGZIP(), []int{6}
}

// AbilityTriggerType 定义能力何时可以被触发。
type AbilityTriggerType int32

const (
	AbilityTriggerType_ABILITY_TRIGGER_TYPE_UNSPECIFIED      AbilityTriggerType = 0
	AbilityTriggerType_ABILITY_TRIGGER_TYPE_DAY_START        AbilityTriggerType = 1 // 天开始时
	AbilityTriggerType_ABILITY_TRIGGER_TYPE_MASTERMIND_PHASE AbilityTriggerType = 2 // 主谋阶段
	AbilityTriggerType_ABILITY_TRIGGER_TYPE_GOODWILL_PHASE   AbilityTriggerType = 3 // 好感阶段
	AbilityTriggerType_ABILITY_TRIGGER_TYPE_PASSIVE          AbilityTriggerType = 4 // 被动
	AbilityTriggerType_ABILITY_TRIGGER_TYPE_CARD_RESOLUTION  AbilityTriggerType = 5 // 卡牌结算阶段
	AbilityTriggerType_ABILITY_TRIGGER_TYPE_INCIDENT         AbilityTriggerType = 6 // 事件发生时
	AbilityTriggerType_ABILITY_TRIGGER_TYPE_PLAYER_ACTION    AbilityTriggerType = 7 // 玩家行动时
)

// Enum value maps for AbilityTriggerType.
var (
	AbilityTriggerType_name = map[int32]string{
		0: "ABILITY_TRIGGER_TYPE_UNSPECIFIED",
		1: "ABILITY_TRIGGER_TYPE_DAY_START",
		2: "ABILITY_TRIGGER_TYPE_MASTERMIND_PHASE",
		3: "ABILITY_TRIGGER_TYPE_GOODWILL_PHASE",
		4: "ABILITY_TRIGGER_TYPE_PASSIVE",
		5: "ABILITY_TRIGGER_TYPE_CARD_RESOLUTION",
		6: "ABILITY_TRIGGER_TYPE_INCIDENT",
		7: "ABILITY_TRIGGER_TYPE_PLAYER_ACTION",
	}
	AbilityTriggerType_value = map[string]int32{
		"ABILITY_TRIGGER_TYPE_UNSPECIFIED":      0,
		"ABILITY_TRIGGER_TYPE_DAY_START":        1,
		"ABILITY_TRIGGER_TYPE_MASTERMIND_PHASE": 2,
		"ABILITY_TRIGGER_TYPE_GOODWILL_PHASE":   3,
		"ABILITY_TRIGGER_TYPE_PASSIVE":          4,
		"ABILITY_TRIGGER_TYPE_CARD_RESOLUTION":  5,
		"ABILITY_TRIGGER_TYPE_INCIDENT":         6,
		"ABILITY_TRIGGER_TYPE_PLAYER_ACTION":    7,
	}
)

func (x AbilityTriggerType) Enum() *AbilityTriggerType {
	p := new(AbilityTriggerType)
	*p = x
	return p
}

func (x AbilityTriggerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AbilityTriggerType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_enums_proto_enumTypes[7].Descriptor()
}

func (AbilityTriggerType) Type() protoreflect.EnumType {
	return &file_proto_v1_enums_proto_enumTypes[7]
}

func (x AbilityTriggerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AbilityTriggerType.Descriptor instead.
func (AbilityTriggerType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_enums_proto_rawDescGZIP(), []int{7}
}

// EffectType 定义能力或卡牌可能产生的效果类型。
// 这是组合方法的核心。
type EffectType int32

const (
	EffectType_EFFECT_TYPE_UNSPECIFIED            EffectType = 0
	EffectType_EFFECT_TYPE_MOVE_CHARACTER         EffectType = 1 // 移动角色
	EffectType_EFFECT_TYPE_ADJUST_PARANOIA        EffectType = 2 // 调整妄想
	EffectType_EFFECT_TYPE_ADJUST_GOODWILL        EffectType = 3 // 调整好感
	EffectType_EFFECT_TYPE_ADJUST_INTRIGUE        EffectType = 4 // 调整阴谋
	EffectType_EFFECT_TYPE_REVEAL_ROLE            EffectType = 5 // 用于特定能力，揭示角色
	EffectType_EFFECT_TYPE_PREVENT_TRAGEDY        EffectType = 6 // 阻止悲剧
	EffectType_EFFECT_TYPE_GRANT_ABILITY          EffectType = 7 // 授予能力
	EffectType_EFFECT_TYPE_CHECK_LOCATION_ALONE   EffectType = 8 // 用于悲剧条件，检查地点是否有人独处
	EffectType_EFFECT_TYPE_CHECK_CHARACTER_STATUS EffectType = 9 // 用于悲剧条件，检查角色状态
)

// Enum value maps for EffectType.
var (
	EffectType_name = map[int32]string{
		0: "EFFECT_TYPE_UNSPECIFIED",
		1: "EFFECT_TYPE_MOVE_CHARACTER",
		2: "EFFECT_TYPE_ADJUST_PARANOIA",
		3: "EFFECT_TYPE_ADJUST_GOODWILL",
		4: "EFFECT_TYPE_ADJUST_INTRIGUE",
		5: "EFFECT_TYPE_REVEAL_ROLE",
		6: "EFFECT_TYPE_PREVENT_TRAGEDY",
		7: "EFFECT_TYPE_GRANT_ABILITY",
		8: "EFFECT_TYPE_CHECK_LOCATION_ALONE",
		9: "EFFECT_TYPE_CHECK_CHARACTER_STATUS",
	}
	EffectType_value = map[string]int32{
		"EFFECT_TYPE_UNSPECIFIED":            0,
		"EFFECT_TYPE_MOVE_CHARACTER":         1,
		"EFFECT_TYPE_ADJUST_PARANOIA":        2,
		"EFFECT_TYPE_ADJUST_GOODWILL":        3,
		"EFFECT_TYPE_ADJUST_INTRIGUE":        4,
		"EFFECT_TYPE_REVEAL_ROLE":            5,
		"EFFECT_TYPE_PREVENT_TRAGEDY":        6,
		"EFFECT_TYPE_GRANT_ABILITY":          7,
		"EFFECT_TYPE_CHECK_LOCATION_ALONE":   8,
		"EFFECT_TYPE_CHECK_CHARACTER_STATUS": 9,
	}
)

func (x EffectType) Enum() *EffectType {
	p := new(EffectType)
	*p = x
	return p
}

func (x EffectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EffectType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_enums_proto_enumTypes[8].Descriptor()
}

func (EffectType) Type() protoreflect.EnumType {
	return &file_proto_v1_enums_proto_enumTypes[8]
}

func (x EffectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EffectType.Descriptor instead.
func (EffectType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_enums_proto_rawDescGZIP(), []int{8}
}

// TargetRuleType 定义悲剧如何选择目标角色。
type TargetRuleType int32

const (
	TargetRuleType_TARGET_RULE_TYPE_UNSPECIFIED               TargetRuleType = 0
	TargetRuleType_TARGET_RULE_TYPE_SPECIFIC_CHARACTER        TargetRuleType = 1 // 特定角色
	TargetRuleType_TARGET_RULE_TYPE_ANY_CHARACTER_AT_LOCATION TargetRuleType = 2 // 在某个地点的任何角色
)

// Enum value maps for TargetRuleType.
var (
	TargetRuleType_name = map[int32]string{
		0: "TARGET_RULE_TYPE_UNSPECIFIED",
		1: "TARGET_RULE_TYPE_SPECIFIC_CHARACTER",
		2: "TARGET_RULE_TYPE_ANY_CHARACTER_AT_LOCATION",
	}
	TargetRuleType_value = map[string]int32{
		"TARGET_RULE_TYPE_UNSPECIFIED":               0,
		"TARGET_RULE_TYPE_SPECIFIC_CHARACTER":        1,
		"TARGET_RULE_TYPE_ANY_CHARACTER_AT_LOCATION": 2,
	}
)

func (x TargetRuleType) Enum() *TargetRuleType {
	p := new(TargetRuleType)
	*p = x
	return p
}

func (x TargetRuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetRuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_enums_proto_enumTypes[9].Descriptor()
}

func (TargetRuleType) Type() protoreflect.EnumType {
	return &file_proto_v1_enums_proto_enumTypes[9]
}

func (x TargetRuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetRuleType.Descriptor instead.
func (TargetRuleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_enums_proto_rawDescGZIP(), []int{9}
}

var File_proto_v1_enums_proto protoreflect.FileDescriptor

const file_proto_v1_enums_proto_rawDesc = "" +
	"\n" +
	"\x14proto/v1/enums.proto\x12\bproto.v1*\x9c\x01\n" +
	"\bCardType\x12\x19\n" +
	"\x15CARD_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CARD_TYPE_MOVEMENT\x10\x01\x12\x16\n" +
	"\x12CARD_TYPE_PARANOIA\x10\x02\x12\x16\n" +
	"\x12CARD_TYPE_GOODWILL\x10\x03\x12\x16\n" +
	"\x12CARD_TYPE_INTRIGUE\x10\x04\x12\x15\n" +
	"\x11CARD_TYPE_SPECIAL\x10\x05*b\n" +
	"\n" +
	"PlayerRole\x12\x1b\n" +
	"\x17PLAYER_ROLE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PLAYER_ROLE_MASTERMIND\x10\x01\x12\x1b\n" +
	"\x17PLAYER_ROLE_PROTAGONIST\x10\x02*\xb3\x02\n" +
	"\tGamePhase\x12\x1a\n" +
	"\x16GAME_PHASE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12GAME_PHASE_MORNING\x10\x01\x12\x18\n" +
	"\x14GAME_PHASE_CARD_PLAY\x10\x02\x12\x1a\n" +
	"\x16GAME_PHASE_CARD_REVEAL\x10\x03\x12\x1b\n" +
	"\x17GAME_PHASE_CARD_RESOLVE\x10\x04\x12\x18\n" +
	"\x14GAME_PHASE_ABILITIES\x10\x05\x12\x18\n" +
	"\x14GAME_PHASE_INCIDENTS\x10\x06\x12\x16\n" +
	"\x12GAME_PHASE_DAY_END\x10\a\x12\x17\n" +
	"\x13GAME_PHASE_LOOP_END\x10\b\x12\x18\n" +
	"\x14GAME_PHASE_GAME_OVER\x10\t\x12 \n" +
	"\x1cGAME_PHASE_PROTAGONIST_GUESS\x10\n" +
	"*\xab\x04\n" +
	"\rGameEventType\x12\x1f\n" +
	"\x1bGAME_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bGAME_EVENT_TYPE_CARD_PLAYED\x10\x01\x12#\n" +
	"\x1fGAME_EVENT_TYPE_CHARACTER_MOVED\x10\x02\x12%\n" +
	"!GAME_EVENT_TYPE_PARANOIA_ADJUSTED\x10\x03\x12%\n" +
	"!GAME_EVENT_TYPE_GOODWILL_ADJUSTED\x10\x04\x12%\n" +
	"!GAME_EVENT_TYPE_INTRIGUE_ADJUSTED\x10\x05\x12 \n" +
	"\x1cGAME_EVENT_TYPE_ABILITY_USED\x10\x06\x12%\n" +
	"!GAME_EVENT_TYPE_TRAGEDY_TRIGGERED\x10\a\x12%\n" +
	"!GAME_EVENT_TYPE_TRAGEDY_PREVENTED\x10\b\x12 \n" +
	"\x1cGAME_EVENT_TYPE_DAY_ADVANCED\x10\t\x12\x1e\n" +
	"\x1aGAME_EVENT_TYPE_LOOP_RESET\x10\n" +
	"\x12\x1d\n" +
	"\x19GAME_EVENT_TYPE_GAME_OVER\x10\v\x12 \n" +
	"\x1cGAME_EVENT_TYPE_PLAYER_GUESS\x10\f\x12#\n" +
	"\x1fGAME_EVENT_TYPE_CHOICE_REQUIRED\x10\r\x12&\n" +
	"\"GAME_EVENT_TYPE_INCIDENT_TRIGGERED\x10\x0e*\xa3\x01\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACTION_TYPE_PLAY_CARD\x10\x01\x12\x1b\n" +
	"\x17ACTION_TYPE_USE_ABILITY\x10\x02\x12\x1a\n" +
	"\x16ACTION_TYPE_MAKE_GUESS\x10\x03\x12$\n" +
	" ACTION_TYPE_READY_FOR_NEXT_PHASE\x10\x04*\x87\x02\n" +
	"\bRoleType\x12\x19\n" +
	"\x15ROLE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ROLE_TYPE_INNOCENT\x10\x01\x12\x14\n" +
	"\x10ROLE_TYPE_KILLER\x10\x02\x12\x13\n" +
	"\x0fROLE_TYPE_BRAIN\x10\x03\x12\x18\n" +
	"\x14ROLE_TYPE_KEY_PERSON\x10\x04\x12\x14\n" +
	"\x10ROLE_TYPE_FRIEND\x10\x05\x12!\n" +
	"\x1dROLE_TYPE_CONSPIRACY_THEORIST\x10\x06\x12\x15\n" +
	"\x11ROLE_TYPE_CULTIST\x10\a\x12\x18\n" +
	"\x14ROLE_TYPE_MASTERMIND\x10\b\x12\x19\n" +
	"\x15ROLE_TYPE_PROTAGONIST\x10\t*w\n" +
	"\vTragedyType\x12\x1c\n" +
	"\x18TRAGEDY_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TRAGEDY_TYPE_MURDER\x10\x01\x12\x18\n" +
	"\x14TRAGEDY_TYPE_SUICIDE\x10\x02\x12\x17\n" +
	"\x13TRAGEDY_TYPE_SEALED\x10\x03*\xc9\x02\n" +
	"\x12AbilityTriggerType\x12$\n" +
	" ABILITY_TRIGGER_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eABILITY_TRIGGER_TYPE_DAY_START\x10\x01\x12)\n" +
	"%ABILITY_TRIGGER_TYPE_MASTERMIND_PHASE\x10\x02\x12'\n" +
	"#ABILITY_TRIGGER_TYPE_GOODWILL_PHASE\x10\x03\x12 \n" +
	"\x1cABILITY_TRIGGER_TYPE_PASSIVE\x10\x04\x12(\n" +
	"$ABILITY_TRIGGER_TYPE_CARD_RESOLUTION\x10\x05\x12!\n" +
	"\x1dABILITY_TRIGGER_TYPE_INCIDENT\x10\x06\x12&\n" +
	"\"ABILITY_TRIGGER_TYPE_PLAYER_ACTION\x10\a*\xd7\x02\n" +
	"\n" +
	"EffectType\x12\x1b\n" +
	"\x17EFFECT_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aEFFECT_TYPE_MOVE_CHARACTER\x10\x01\x12\x1f\n" +
	"\x1bEFFECT_TYPE_ADJUST_PARANOIA\x10\x02\x12\x1f\n" +
	"\x1bEFFECT_TYPE_ADJUST_GOODWILL\x10\x03\x12\x1f\n" +
	"\x1bEFFECT_TYPE_ADJUST_INTRIGUE\x10\x04\x12\x1b\n" +
	"\x17EFFECT_TYPE_REVEAL_ROLE\x10\x05\x12\x1f\n" +
	"\x1bEFFECT_TYPE_PREVENT_TRAGEDY\x10\x06\x12\x1d\n" +
	"\x19EFFECT_TYPE_GRANT_ABILITY\x10\a\x12$\n" +
	" EFFECT_TYPE_CHECK_LOCATION_ALONE\x10\b\x12&\n" +
	"\"EFFECT_TYPE_CHECK_CHARACTER_STATUS\x10\t*\x8b\x01\n" +
	"\x0eTargetRuleType\x12 \n" +
	"\x1cTARGET_RULE_TYPE_UNSPECIFIED\x10\x00\x12'\n" +
	"#TARGET_RULE_TYPE_SPECIFIC_CHARACTER\x10\x01\x12.\n" +
	"*TARGET_RULE_TYPE_ANY_CHARACTER_AT_LOCATION\x10\x02B\"Z github.com/user/repo/proto/modelb\x06proto3"

var (
	file_proto_v1_enums_proto_rawDescOnce sync.Once
	file_proto_v1_enums_proto_rawDescData []byte
)

func file_proto_v1_enums_proto_rawDescGZIP() []byte {
	file_proto_v1_enums_proto_rawDescOnce.Do(func() {
		file_proto_v1_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_enums_proto_rawDesc), len(file_proto_v1_enums_proto_rawDesc)))
	})
	return file_proto_v1_enums_proto_rawDescData
}

var file_proto_v1_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_proto_v1_enums_proto_goTypes = []any{
	(CardType)(0),           // 0: proto.v1.CardType
	(PlayerRole)(0),         // 1: proto.v1.PlayerRole
	(GamePhase)(0),          // 2: proto.v1.GamePhase
	(GameEventType)(0),      // 3: proto.v1.GameEventType
	(ActionType)(0),         // 4: proto.v1.ActionType
	(RoleType)(0),           // 5: proto.v1.RoleType
	(TragedyType)(0),        // 6: proto.v1.TragedyType
	(AbilityTriggerType)(0), // 7: proto.v1.AbilityTriggerType
	(EffectType)(0),         // 8: proto.v1.EffectType
	(TargetRuleType)(0),     // 9: proto.v1.TargetRuleType
}
var file_proto_v1_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_enums_proto_init() }
func file_proto_v1_enums_proto_init() {
	if File_proto_v1_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_enums_proto_rawDesc), len(file_proto_v1_enums_proto_rawDesc)),
			NumEnums:      10,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_enums_proto_goTypes,
		DependencyIndexes: file_proto_v1_enums_proto_depIdxs,
		EnumInfos:         file_proto_v1_enums_proto_enumTypes,
	}.Build()
	File_proto_v1_enums_proto = out.File
	file_proto_v1_enums_proto_goTypes = nil
	file_proto_v1_enums_proto_depIdxs = nil
}
