// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/event.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GameEvent 表示游戏中发生的事件。
type GameEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          GameEventType          `protobuf:"varint,1,opt,name=type,proto3,enum=v1.GameEventType" json:"type,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *GameEvent) GetType() GameEventType {
	if x != nil {
		return x.Type
	}
	return GameEventType_GAME_EVENT_TYPE_UNSPECIFIED
}

func (x *GameEvent) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GameEventLib struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        map[int32]*anypb.Any   `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEventLib) Reset() {
	*x = GameEventLib{}
	mi := &file_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEventLib) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEventLib) ProtoMessage() {}

func (x *GameEventLib) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEventLib.ProtoReflect.Descriptor instead.
func (*GameEventLib) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *GameEventLib) GetEvents() map[int32]*anypb.Any {
	if x != nil {
		return x.Events
	}
	return nil
}

type CharacterMovedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int32                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	NewLocation   LocationType           `protobuf:"varint,2,opt,name=new_location,json=newLocation,proto3,enum=v1.LocationType" json:"new_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterMovedEvent) Reset() {
	*x = CharacterMovedEvent{}
	mi := &file_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterMovedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMovedEvent) ProtoMessage() {}

func (x *CharacterMovedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMovedEvent.ProtoReflect.Descriptor instead.
func (*CharacterMovedEvent) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *CharacterMovedEvent) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CharacterMovedEvent) GetNewLocation() LocationType {
	if x != nil {
		return x.NewLocation
	}
	return LocationType_LOCATION_TYPE_UNSPECIFIED
}

type ParanoiaAdjustedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int32                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	NewParanoia   int32                  `protobuf:"varint,3,opt,name=new_paranoia,json=newParanoia,proto3" json:"new_paranoia,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParanoiaAdjustedEvent) Reset() {
	*x = ParanoiaAdjustedEvent{}
	mi := &file_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParanoiaAdjustedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParanoiaAdjustedEvent) ProtoMessage() {}

func (x *ParanoiaAdjustedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParanoiaAdjustedEvent.ProtoReflect.Descriptor instead.
func (*ParanoiaAdjustedEvent) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *ParanoiaAdjustedEvent) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *ParanoiaAdjustedEvent) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ParanoiaAdjustedEvent) GetNewParanoia() int32 {
	if x != nil {
		return x.NewParanoia
	}
	return 0
}

type GoodwillAdjustedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int32                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	NewGoodwill   int32                  `protobuf:"varint,3,opt,name=new_goodwill,json=newGoodwill,proto3" json:"new_goodwill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodwillAdjustedEvent) Reset() {
	*x = GoodwillAdjustedEvent{}
	mi := &file_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodwillAdjustedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodwillAdjustedEvent) ProtoMessage() {}

func (x *GoodwillAdjustedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodwillAdjustedEvent.ProtoReflect.Descriptor instead.
func (*GoodwillAdjustedEvent) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{4}
}

func (x *GoodwillAdjustedEvent) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *GoodwillAdjustedEvent) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GoodwillAdjustedEvent) GetNewGoodwill() int32 {
	if x != nil {
		return x.NewGoodwill
	}
	return 0
}

type IntrigueAdjustedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int32                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	NewIntrigue   int32                  `protobuf:"varint,3,opt,name=new_intrigue,json=newIntrigue,proto3" json:"new_intrigue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrigueAdjustedEvent) Reset() {
	*x = IntrigueAdjustedEvent{}
	mi := &file_v1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrigueAdjustedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrigueAdjustedEvent) ProtoMessage() {}

func (x *IntrigueAdjustedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrigueAdjustedEvent.ProtoReflect.Descriptor instead.
func (*IntrigueAdjustedEvent) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{5}
}

func (x *IntrigueAdjustedEvent) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *IntrigueAdjustedEvent) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *IntrigueAdjustedEvent) GetNewIntrigue() int32 {
	if x != nil {
		return x.NewIntrigue
	}
	return 0
}

type LoopLossEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncidentType  IncidentType           `protobuf:"varint,1,opt,name=incident_type,json=incidentType,proto3,enum=v1.IncidentType" json:"incident_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoopLossEvent) Reset() {
	*x = LoopLossEvent{}
	mi := &file_v1_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopLossEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopLossEvent) ProtoMessage() {}

func (x *LoopLossEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopLossEvent.ProtoReflect.Descriptor instead.
func (*LoopLossEvent) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{6}
}

func (x *LoopLossEvent) GetIncidentType() IncidentType {
	if x != nil {
		return x.IncidentType
	}
	return IncidentType_INCIDENT_TYPE_UNSPECIFIED
}

type LoopWinEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoopWinEvent) Reset() {
	*x = LoopWinEvent{}
	mi := &file_v1_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopWinEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopWinEvent) ProtoMessage() {}

func (x *LoopWinEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopWinEvent.ProtoReflect.Descriptor instead.
func (*LoopWinEvent) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{7}
}

type AbilityUsedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int32                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	AbilityName   string                 `protobuf:"bytes,2,opt,name=ability_name,json=abilityName,proto3" json:"ability_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbilityUsedEvent) Reset() {
	*x = AbilityUsedEvent{}
	mi := &file_v1_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbilityUsedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityUsedEvent) ProtoMessage() {}

func (x *AbilityUsedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityUsedEvent.ProtoReflect.Descriptor instead.
func (*AbilityUsedEvent) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{8}
}

func (x *AbilityUsedEvent) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *AbilityUsedEvent) GetAbilityName() string {
	if x != nil {
		return x.AbilityName
	}
	return ""
}

type DayAdvancedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           int32                  `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Loop          int32                  `protobuf:"varint,2,opt,name=loop,proto3" json:"loop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayAdvancedEvent) Reset() {
	*x = DayAdvancedEvent{}
	mi := &file_v1_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayAdvancedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayAdvancedEvent) ProtoMessage() {}

func (x *DayAdvancedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayAdvancedEvent.ProtoReflect.Descriptor instead.
func (*DayAdvancedEvent) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{9}
}

func (x *DayAdvancedEvent) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *DayAdvancedEvent) GetLoop() int32 {
	if x != nil {
		return x.Loop
	}
	return 0
}

type CardPlayedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayedCards   map[int32]*CardList    `protobuf:"bytes,1,rep,name=played_cards,json=playedCards,proto3" json:"played_cards,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardPlayedEvent) Reset() {
	*x = CardPlayedEvent{}
	mi := &file_v1_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardPlayedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardPlayedEvent) ProtoMessage() {}

func (x *CardPlayedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardPlayedEvent.ProtoReflect.Descriptor instead.
func (*CardPlayedEvent) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{10}
}

func (x *CardPlayedEvent) GetPlayedCards() map[int32]*CardList {
	if x != nil {
		return x.PlayedCards
	}
	return nil
}

type LoopResetEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loop          int32                  `protobuf:"varint,1,opt,name=loop,proto3" json:"loop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoopResetEvent) Reset() {
	*x = LoopResetEvent{}
	mi := &file_v1_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopResetEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopResetEvent) ProtoMessage() {}

func (x *LoopResetEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopResetEvent.ProtoReflect.Descriptor instead.
func (*LoopResetEvent) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{11}
}

func (x *LoopResetEvent) GetLoop() int32 {
	if x != nil {
		return x.Loop
	}
	return 0
}

type GameOverEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Winner        PlayerRole             `protobuf:"varint,1,opt,name=winner,proto3,enum=v1.PlayerRole" json:"winner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOverEvent) Reset() {
	*x = GameOverEvent{}
	mi := &file_v1_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOverEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOverEvent) ProtoMessage() {}

func (x *GameOverEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOverEvent.ProtoReflect.Descriptor instead.
func (*GameOverEvent) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{12}
}

func (x *GameOverEvent) GetWinner() PlayerRole {
	if x != nil {
		return x.Winner
	}
	return PlayerRole_PLAYER_ROLE_UNSPECIFIED
}

// Choice 表示玩家可以做出的选择。
type Choice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	CharacterId   int32                  `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_v1_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choice.ProtoReflect.Descriptor instead.
func (*Choice) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{13}
}

func (x *Choice) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Choice) GetCharacterId() int32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type ChoiceRequiredEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 这可能需要更复杂的结构，具体取决于选择
	Choices       []*Choice `protobuf:"bytes,1,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChoiceRequiredEvent) Reset() {
	*x = ChoiceRequiredEvent{}
	mi := &file_v1_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChoiceRequiredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoiceRequiredEvent) ProtoMessage() {}

func (x *ChoiceRequiredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoiceRequiredEvent.ProtoReflect.Descriptor instead.
func (*ChoiceRequiredEvent) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{14}
}

func (x *ChoiceRequiredEvent) GetChoices() []*Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

type Incident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Day           int32                  `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	Culprit       string                 `protobuf:"bytes,3,opt,name=culprit,proto3" json:"culprit,omitempty"`
	Victim        string                 `protobuf:"bytes,4,opt,name=victim,proto3" json:"victim,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Incident) Reset() {
	*x = Incident{}
	mi := &file_v1_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{15}
}

func (x *Incident) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Incident) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *Incident) GetCulprit() string {
	if x != nil {
		return x.Culprit
	}
	return ""
}

func (x *Incident) GetVictim() string {
	if x != nil {
		return x.Victim
	}
	return ""
}

func (x *Incident) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type IncidentTriggeredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incident      *Incident              `protobuf:"bytes,1,opt,name=incident,proto3" json:"incident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncidentTriggeredEvent) Reset() {
	*x = IncidentTriggeredEvent{}
	mi := &file_v1_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncidentTriggeredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncidentTriggeredEvent) ProtoMessage() {}

func (x *IncidentTriggeredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncidentTriggeredEvent.ProtoReflect.Descriptor instead.
func (*IncidentTriggeredEvent) Descriptor() ([]byte, []int) {
	return file_v1_event_proto_rawDescGZIP(), []int{16}
}

func (x *IncidentTriggeredEvent) GetIncident() *Incident {
	if x != nil {
		return x.Incident
	}
	return nil
}

var File_v1_event_proto protoreflect.FileDescriptor

const file_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/event.proto\x12\x02v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\rv1/card.proto\x1a\x0ev1/enums.proto\"\x9c\x01\n" +
	"\tGameEvent\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.v1.GameEventTypeR\x04type\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\apayload\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x95\x01\n" +
	"\fGameEventLib\x124\n" +
	"\x06events\x18\x01 \x03(\v2\x1c.v1.GameEventLib.EventsEntryR\x06events\x1aO\n" +
	"\vEventsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"m\n" +
	"\x13CharacterMovedEvent\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x05R\vcharacterId\x123\n" +
	"\fnew_location\x18\x02 \x01(\x0e2\x10.v1.LocationTypeR\vnewLocation\"u\n" +
	"\x15ParanoiaAdjustedEvent\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x05R\vcharacterId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12!\n" +
	"\fnew_paranoia\x18\x03 \x01(\x05R\vnewParanoia\"u\n" +
	"\x15GoodwillAdjustedEvent\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x05R\vcharacterId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12!\n" +
	"\fnew_goodwill\x18\x03 \x01(\x05R\vnewGoodwill\"u\n" +
	"\x15IntrigueAdjustedEvent\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x05R\vcharacterId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12!\n" +
	"\fnew_intrigue\x18\x03 \x01(\x05R\vnewIntrigue\"F\n" +
	"\rLoopLossEvent\x125\n" +
	"\rincident_type\x18\x01 \x01(\x0e2\x10.v1.IncidentTypeR\fincidentType\"\x0e\n" +
	"\fLoopWinEvent\"X\n" +
	"\x10AbilityUsedEvent\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x05R\vcharacterId\x12!\n" +
	"\fability_name\x18\x02 \x01(\tR\vabilityName\"8\n" +
	"\x10DayAdvancedEvent\x12\x10\n" +
	"\x03day\x18\x01 \x01(\x05R\x03day\x12\x12\n" +
	"\x04loop\x18\x02 \x01(\x05R\x04loop\"\xa8\x01\n" +
	"\x0fCardPlayedEvent\x12G\n" +
	"\fplayed_cards\x18\x01 \x03(\v2$.v1.CardPlayedEvent.PlayedCardsEntryR\vplayedCards\x1aL\n" +
	"\x10PlayedCardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.v1.CardListR\x05value:\x028\x01\"$\n" +
	"\x0eLoopResetEvent\x12\x12\n" +
	"\x04loop\x18\x01 \x01(\x05R\x04loop\"7\n" +
	"\rGameOverEvent\x12&\n" +
	"\x06winner\x18\x01 \x01(\x0e2\x0e.v1.PlayerRoleR\x06winner\"M\n" +
	"\x06Choice\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\x05R\vcharacterId\";\n" +
	"\x13ChoiceRequiredEvent\x12$\n" +
	"\achoices\x18\x01 \x03(\v2\n" +
	".v1.ChoiceR\achoices\"\x84\x01\n" +
	"\bIncident\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03day\x18\x02 \x01(\x05R\x03day\x12\x18\n" +
	"\aculprit\x18\x03 \x01(\tR\aculprit\x12\x16\n" +
	"\x06victim\x18\x04 \x01(\tR\x06victim\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"B\n" +
	"\x16IncidentTriggeredEvent\x12(\n" +
	"\bincident\x18\x01 \x01(\v2\f.v1.IncidentR\bincidentB#Z!tragedylooper/internal/game/v1;v1b\x06proto3"

var (
	file_v1_event_proto_rawDescOnce sync.Once
	file_v1_event_proto_rawDescData []byte
)

func file_v1_event_proto_rawDescGZIP() []byte {
	file_v1_event_proto_rawDescOnce.Do(func() {
		file_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_event_proto_rawDesc), len(file_v1_event_proto_rawDesc)))
	})
	return file_v1_event_proto_rawDescData
}

var file_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_v1_event_proto_goTypes = []any{
	(*GameEvent)(nil),              // 0: v1.GameEvent
	(*GameEventLib)(nil),           // 1: v1.GameEventLib
	(*CharacterMovedEvent)(nil),    // 2: v1.CharacterMovedEvent
	(*ParanoiaAdjustedEvent)(nil),  // 3: v1.ParanoiaAdjustedEvent
	(*GoodwillAdjustedEvent)(nil),  // 4: v1.GoodwillAdjustedEvent
	(*IntrigueAdjustedEvent)(nil),  // 5: v1.IntrigueAdjustedEvent
	(*LoopLossEvent)(nil),          // 6: v1.LoopLossEvent
	(*LoopWinEvent)(nil),           // 7: v1.LoopWinEvent
	(*AbilityUsedEvent)(nil),       // 8: v1.AbilityUsedEvent
	(*DayAdvancedEvent)(nil),       // 9: v1.DayAdvancedEvent
	(*CardPlayedEvent)(nil),        // 10: v1.CardPlayedEvent
	(*LoopResetEvent)(nil),         // 11: v1.LoopResetEvent
	(*GameOverEvent)(nil),          // 12: v1.GameOverEvent
	(*Choice)(nil),                 // 13: v1.Choice
	(*ChoiceRequiredEvent)(nil),    // 14: v1.ChoiceRequiredEvent
	(*Incident)(nil),               // 15: v1.Incident
	(*IncidentTriggeredEvent)(nil), // 16: v1.IncidentTriggeredEvent
	nil,                            // 17: v1.GameEventLib.EventsEntry
	nil,                            // 18: v1.CardPlayedEvent.PlayedCardsEntry
	(GameEventType)(0),             // 19: v1.GameEventType
	(*anypb.Any)(nil),              // 20: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),  // 21: google.protobuf.Timestamp
	(LocationType)(0),              // 22: v1.LocationType
	(IncidentType)(0),              // 23: v1.IncidentType
	(PlayerRole)(0),                // 24: v1.PlayerRole
	(*CardList)(nil),               // 25: v1.CardList
}
var file_v1_event_proto_depIdxs = []int32{
	19, // 0: v1.GameEvent.type:type_name -> v1.GameEventType
	20, // 1: v1.GameEvent.payload:type_name -> google.protobuf.Any
	21, // 2: v1.GameEvent.timestamp:type_name -> google.protobuf.Timestamp
	17, // 3: v1.GameEventLib.events:type_name -> v1.GameEventLib.EventsEntry
	22, // 4: v1.CharacterMovedEvent.new_location:type_name -> v1.LocationType
	23, // 5: v1.LoopLossEvent.incident_type:type_name -> v1.IncidentType
	18, // 6: v1.CardPlayedEvent.played_cards:type_name -> v1.CardPlayedEvent.PlayedCardsEntry
	24, // 7: v1.GameOverEvent.winner:type_name -> v1.PlayerRole
	13, // 8: v1.ChoiceRequiredEvent.choices:type_name -> v1.Choice
	15, // 9: v1.IncidentTriggeredEvent.incident:type_name -> v1.Incident
	20, // 10: v1.GameEventLib.EventsEntry.value:type_name -> google.protobuf.Any
	25, // 11: v1.CardPlayedEvent.PlayedCardsEntry.value:type_name -> v1.CardList
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_event_proto_init() }
func file_v1_event_proto_init() {
	if File_v1_event_proto != nil {
		return
	}
	file_v1_card_proto_init()
	file_v1_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_event_proto_rawDesc), len(file_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_event_proto_goTypes,
		DependencyIndexes: file_v1_event_proto_depIdxs,
		MessageInfos:      file_v1_event_proto_msgTypes,
	}.Build()
	File_v1_event_proto = out.File
	file_v1_event_proto_goTypes = nil
	file_v1_event_proto_depIdxs = nil
}
