// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/v1/script.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Script 定义一个特定的游戏场景。
type Script struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                               // 唯一标识符
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                            // 剧本名称
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                              // 剧本描述
	MainPlot       string                 `protobuf:"bytes,4,opt,name=main_plot,json=mainPlot,proto3" json:"main_plot,omitempty"`                    // 主线剧情
	SubPlots       []string               `protobuf:"bytes,5,rep,name=sub_plots,json=subPlots,proto3" json:"sub_plots,omitempty"`                    // 支线剧情
	Characters     []*CharacterConfig     `protobuf:"bytes,6,rep,name=characters,proto3" json:"characters,omitempty"`                                // 角色配置
	Tragedies      []*TragedyCondition    `protobuf:"bytes,7,rep,name=tragedies,proto3" json:"tragedies,omitempty"`                                  // 悲剧条件
	LoopCount      int32                  `protobuf:"varint,8,opt,name=loop_count,json=loopCount,proto3" json:"loop_count,omitempty"`                // 循环总次数
	DaysPerLoop    int32                  `protobuf:"varint,9,opt,name=days_per_loop,json=daysPerLoop,proto3" json:"days_per_loop,omitempty"`        // 每循环天数
	WinConditions  []string               `protobuf:"bytes,10,rep,name=win_conditions,json=winConditions,proto3" json:"win_conditions,omitempty"`    // 胜利条件
	LoseConditions []string               `protobuf:"bytes,11,rep,name=lose_conditions,json=loseConditions,proto3" json:"lose_conditions,omitempty"` // 失败条件
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Script) Reset() {
	*x = Script{}
	mi := &file_proto_v1_script_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Script) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Script) ProtoMessage() {}

func (x *Script) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_script_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Script.ProtoReflect.Descriptor instead.
func (*Script) Descriptor() ([]byte, []int) {
	return file_proto_v1_script_proto_rawDescGZIP(), []int{0}
}

func (x *Script) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Script) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Script) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Script) GetMainPlot() string {
	if x != nil {
		return x.MainPlot
	}
	return ""
}

func (x *Script) GetSubPlots() []string {
	if x != nil {
		return x.SubPlots
	}
	return nil
}

func (x *Script) GetCharacters() []*CharacterConfig {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *Script) GetTragedies() []*TragedyCondition {
	if x != nil {
		return x.Tragedies
	}
	return nil
}

func (x *Script) GetLoopCount() int32 {
	if x != nil {
		return x.LoopCount
	}
	return 0
}

func (x *Script) GetDaysPerLoop() int32 {
	if x != nil {
		return x.DaysPerLoop
	}
	return 0
}

func (x *Script) GetWinConditions() []string {
	if x != nil {
		return x.WinConditions
	}
	return nil
}

func (x *Script) GetLoseConditions() []string {
	if x != nil {
		return x.LoseConditions
	}
	return nil
}

var File_proto_v1_script_proto protoreflect.FileDescriptor

const file_proto_v1_script_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/script.proto\x12\bproto.v1\x1a\x18proto/v1/character.proto\x1a\x16proto/v1/tragedy.proto\"\x90\x03\n" +
	"\x06Script\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tmain_plot\x18\x04 \x01(\tR\bmainPlot\x12\x1b\n" +
	"\tsub_plots\x18\x05 \x03(\tR\bsubPlots\x129\n" +
	"\n" +
	"characters\x18\x06 \x03(\v2\x19.proto.v1.CharacterConfigR\n" +
	"characters\x128\n" +
	"\ttragedies\x18\a \x03(\v2\x1a.proto.v1.TragedyConditionR\ttragedies\x12\x1d\n" +
	"\n" +
	"loop_count\x18\b \x01(\x05R\tloopCount\x12\"\n" +
	"\rdays_per_loop\x18\t \x01(\x05R\vdaysPerLoop\x12%\n" +
	"\x0ewin_conditions\x18\n" +
	" \x03(\tR\rwinConditions\x12'\n" +
	"\x0flose_conditions\x18\v \x03(\tR\x0eloseConditionsB\"Z github.com/user/repo/proto/modelb\x06proto3"

var (
	file_proto_v1_script_proto_rawDescOnce sync.Once
	file_proto_v1_script_proto_rawDescData []byte
)

func file_proto_v1_script_proto_rawDescGZIP() []byte {
	file_proto_v1_script_proto_rawDescOnce.Do(func() {
		file_proto_v1_script_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_script_proto_rawDesc), len(file_proto_v1_script_proto_rawDesc)))
	})
	return file_proto_v1_script_proto_rawDescData
}

var file_proto_v1_script_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_script_proto_goTypes = []any{
	(*Script)(nil),           // 0: proto.v1.Script
	(*CharacterConfig)(nil),  // 1: proto.v1.CharacterConfig
	(*TragedyCondition)(nil), // 2: proto.v1.TragedyCondition
}
var file_proto_v1_script_proto_depIdxs = []int32{
	1, // 0: proto.v1.Script.characters:type_name -> proto.v1.CharacterConfig
	2, // 1: proto.v1.Script.tragedies:type_name -> proto.v1.TragedyCondition
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_script_proto_init() }
func file_proto_v1_script_proto_init() {
	if File_proto_v1_script_proto != nil {
		return
	}
	file_proto_v1_character_proto_init()
	file_proto_v1_tragedy_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_script_proto_rawDesc), len(file_proto_v1_script_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_script_proto_goTypes,
		DependencyIndexes: file_proto_v1_script_proto_depIdxs,
		MessageInfos:      file_proto_v1_script_proto_msgTypes,
	}.Build()
	File_proto_v1_script_proto = out.File
	file_proto_v1_script_proto_goTypes = nil
	file_proto_v1_script_proto_depIdxs = nil
}
